import React, { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';

import { Alert } from '../../components/ui/Alert';
import { Card } from '../../components/ui/Card';
import { Input } from '../../components/ui/Input';
import { LoadingState } from '../../components/ui/LoadingState';
import { labService, ListEntriesResponse } from '../../services/labService';

export function EntriesTab() {
  const navigate = useNavigate();
  const [modelFilter, setModelFilter] = useState('');

  const entriesQuery = useQuery<ListEntriesResponse | null>({
    queryKey: ['lab', 'entries'],
    queryFn: () => labService.listEntries({ limit: 100 }),
  });

  const items = entriesQuery.data?.items ?? [];

  const filteredItems = useMemo(() => {
    if (!modelFilter.trim()) return items;
    const lower = modelFilter.toLowerCase();
    return items.filter(
      (e) =>
        e.model_name.toLowerCase().includes(lower) ||
        e.calcutta_name.toLowerCase().includes(lower)
    );
  }, [items, modelFilter]);

  const formatDate = (dateStr: string) => {
    const d = new Date(dateStr);
    return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
  };

  return (
    <Card>
      <h2 className="text-xl font-semibold mb-4">Lab Entries</h2>
      <p className="text-sm text-gray-600 mb-4">
        Entries are bids generated by investment models for specific calcuttas.
      </p>

      <div className="mb-4">
        <Input
          type="text"
          placeholder="Filter by model or calcutta name..."
          value={modelFilter}
          onChange={(e) => setModelFilter(e.target.value)}
          className="max-w-sm"
        />
      </div>

      {entriesQuery.isLoading ? <LoadingState label="Loading entries..." layout="inline" /> : null}

      {entriesQuery.isError ? (
        <Alert variant="error">Failed to load entries.</Alert>
      ) : null}

      {!entriesQuery.isLoading && !entriesQuery.isError && filteredItems.length === 0 ? (
        <Alert variant="info">No entries found.</Alert>
      ) : null}

      {!entriesQuery.isLoading && !entriesQuery.isError && filteredItems.length > 0 ? (
        <div className="overflow-x-auto">
          <table className="min-w-full divide-y divide-gray-200">
            <thead className="bg-gray-50">
              <tr>
                <th className="px-3 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Model
                </th>
                <th className="px-3 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Calcutta
                </th>
                <th className="px-3 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  State
                </th>
                <th className="px-3 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Optimizer
                </th>
                <th className="px-3 py-2 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Evaluations
                </th>
                <th className="px-3 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Created
                </th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {filteredItems.map((row) => (
                <tr
                  key={row.id}
                  className="hover:bg-gray-50 cursor-pointer"
                  onClick={() => navigate(`/lab/entries/${encodeURIComponent(row.id)}`)}
                >
                  <td className="px-3 py-2 text-sm text-gray-900">
                    <div className="font-medium">{row.model_name}</div>
                    <div className="text-xs text-gray-500">{row.model_kind}</div>
                  </td>
                  <td className="px-3 py-2 text-sm text-gray-700">{row.calcutta_name}</td>
                  <td className="px-3 py-2 text-sm text-gray-600">{row.starting_state_key}</td>
                  <td className="px-3 py-2 text-sm text-gray-600">{row.optimizer_kind}</td>
                  <td className="px-3 py-2 text-sm text-gray-700 text-right">{row.n_evaluations}</td>
                  <td className="px-3 py-2 text-sm text-gray-500">{formatDate(row.created_at)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      ) : null}
    </Card>
  );
}
