// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth_sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthSession = `-- name: CreateAuthSession :one
INSERT INTO auth_sessions (user_id, refresh_token_hash, expires_at, user_agent, ip_address)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateAuthSessionParams struct {
	UserID           string
	RefreshTokenHash string
	ExpiresAt        pgtype.Timestamptz
	UserAgent        *string
	IpAddress        *string
}

func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (string, error) {
	row := q.db.QueryRow(ctx, createAuthSession,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.IpAddress,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getAuthSessionByID = `-- name: GetAuthSessionByID :one
SELECT id, user_id, refresh_token_hash, expires_at, revoked_at
FROM auth_sessions
WHERE id = $1
`

type GetAuthSessionByIDRow struct {
	ID               string
	UserID           string
	RefreshTokenHash string
	ExpiresAt        pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
}

func (q *Queries) GetAuthSessionByID(ctx context.Context, id string) (GetAuthSessionByIDRow, error) {
	row := q.db.QueryRow(ctx, getAuthSessionByID, id)
	var i GetAuthSessionByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAuthSessionByRefreshTokenHash = `-- name: GetAuthSessionByRefreshTokenHash :one
SELECT id, user_id, refresh_token_hash, expires_at, revoked_at
FROM auth_sessions
WHERE refresh_token_hash = $1
`

type GetAuthSessionByRefreshTokenHashRow struct {
	ID               string
	UserID           string
	RefreshTokenHash string
	ExpiresAt        pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
}

func (q *Queries) GetAuthSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (GetAuthSessionByRefreshTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getAuthSessionByRefreshTokenHash, refreshTokenHash)
	var i GetAuthSessionByRefreshTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeAuthSession = `-- name: RevokeAuthSession :exec
UPDATE auth_sessions
SET revoked_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeAuthSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, revokeAuthSession, id)
	return err
}

const rotateAuthSessionRefreshToken = `-- name: RotateAuthSessionRefreshToken :exec
UPDATE auth_sessions
SET refresh_token_hash = $2,
    expires_at = $3,
    updated_at = NOW(),
    last_used_at = NOW()
WHERE id = $1
  AND revoked_at IS NULL
`

type RotateAuthSessionRefreshTokenParams struct {
	ID               string
	RefreshTokenHash string
	ExpiresAt        pgtype.Timestamptz
}

func (q *Queries) RotateAuthSessionRefreshToken(ctx context.Context, arg RotateAuthSessionRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, rotateAuthSessionRefreshToken, arg.ID, arg.RefreshTokenHash, arg.ExpiresAt)
	return err
}
