// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: authz.sql

package sqlc

import (
	"context"
)

const ensureBootstrapGlobalAdmin = `-- name: EnsureBootstrapGlobalAdmin :exec
INSERT INTO grants (user_id, scope_type, scope_id, label_id)
SELECT $1, 'global', NULL, l.id
FROM labels l
WHERE l.key = 'global_admin'
  AND l.deleted_at IS NULL
  AND NOT EXISTS (
    SELECT 1
    FROM grants g
    JOIN labels l2 ON g.label_id = l2.id
    WHERE g.scope_type = 'global'
      AND g.revoked_at IS NULL
      AND l2.key = 'global_admin'
      AND l2.deleted_at IS NULL
  )
`

func (q *Queries) EnsureBootstrapGlobalAdmin(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, ensureBootstrapGlobalAdmin, userID)
	return err
}

const hasPermission = `-- name: HasPermission :one
SELECT 1
FROM grants g
LEFT JOIN permissions p_direct ON g.permission_id = p_direct.id AND p_direct.deleted_at IS NULL
LEFT JOIN labels l ON g.label_id = l.id AND l.deleted_at IS NULL
LEFT JOIN label_permissions lp ON lp.label_id = l.id
LEFT JOIN permissions p_label ON lp.permission_id = p_label.id AND p_label.deleted_at IS NULL
WHERE g.user_id = $1
  AND g.revoked_at IS NULL
  AND (g.expires_at IS NULL OR g.expires_at > NOW())
  AND (
    g.scope_type = 'global'
    OR (g.scope_type = $2 AND g.scope_id = NULLIF($3, '')::uuid)
  )
  AND ($4 = p_direct.key OR $4 = p_label.key)
LIMIT 1
`

type HasPermissionParams struct {
	UserID    string
	ScopeType string
	Column3   interface{}
	Key       string
}

func (q *Queries) HasPermission(ctx context.Context, arg HasPermissionParams) (int32, error) {
	row := q.db.QueryRow(ctx, hasPermission,
		arg.UserID,
		arg.ScopeType,
		arg.Column3,
		arg.Key,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
