// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: authz.sql

package sqlc

import (
	"context"
)

const hasPermission = `-- name: HasPermission :one
SELECT 1
FROM core.grants g
LEFT JOIN core.permissions p_direct ON g.permission_id = p_direct.id AND p_direct.deleted_at IS NULL
LEFT JOIN core.labels l ON g.label_id = l.id AND l.deleted_at IS NULL
LEFT JOIN core.label_permissions lp ON lp.label_id = l.id AND lp.deleted_at IS NULL
LEFT JOIN core.permissions p_label ON lp.permission_id = p_label.id AND p_label.deleted_at IS NULL
WHERE g.user_id = $1
  AND g.deleted_at IS NULL
  AND g.revoked_at IS NULL
  AND (g.expires_at IS NULL OR g.expires_at > NOW())
  AND (
    g.scope_type = 'global'
    OR (g.scope_type = $2 AND g.scope_id = NULLIF($3, '')::uuid)
  )
  AND ($4 = p_direct.key OR $4 = p_label.key)
LIMIT 1
`

type HasPermissionParams struct {
	UserID    string
	ScopeType string
	Column3   interface{}
	Key       string
}

func (q *Queries) HasPermission(ctx context.Context, arg HasPermissionParams) (int32, error) {
	row := q.db.QueryRow(ctx, hasPermission,
		arg.UserID,
		arg.ScopeType,
		arg.Column3,
		arg.Key,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
