// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: calcutta_portfolios.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPortfolio = `-- name: CreatePortfolio :exec
INSERT INTO calcutta_portfolios (id, entry_id, maximum_points, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreatePortfolioParams struct {
	ID            string
	EntryID       string
	MaximumPoints pgtype.Numeric
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) CreatePortfolio(ctx context.Context, arg CreatePortfolioParams) error {
	_, err := q.db.Exec(ctx, createPortfolio,
		arg.ID,
		arg.EntryID,
		arg.MaximumPoints,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getPortfolioByID = `-- name: GetPortfolioByID :one
SELECT
    id,
    entry_id,
    maximum_points::float8 AS maximum_points,
    created_at,
    updated_at,
    deleted_at
FROM calcutta_portfolios
WHERE id = $1 AND deleted_at IS NULL
`

type GetPortfolioByIDRow struct {
	ID            string
	EntryID       string
	MaximumPoints float64
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

func (q *Queries) GetPortfolioByID(ctx context.Context, id string) (GetPortfolioByIDRow, error) {
	row := q.db.QueryRow(ctx, getPortfolioByID, id)
	var i GetPortfolioByIDRow
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.MaximumPoints,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPortfolios = `-- name: ListPortfolios :many
SELECT
    id,
    entry_id,
    maximum_points::float8 AS maximum_points,
    created_at,
    updated_at,
    deleted_at
FROM calcutta_portfolios
WHERE entry_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

type ListPortfoliosRow struct {
	ID            string
	EntryID       string
	MaximumPoints float64
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

func (q *Queries) ListPortfolios(ctx context.Context, entryID string) ([]ListPortfoliosRow, error) {
	rows, err := q.db.Query(ctx, listPortfolios, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPortfoliosRow
	for rows.Next() {
		var i ListPortfoliosRow
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.MaximumPoints,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPortfoliosByEntryID = `-- name: ListPortfoliosByEntryID :many
SELECT id, entry_id, created_at, updated_at, deleted_at
FROM calcutta_portfolios
WHERE entry_id = $1 AND deleted_at IS NULL
`

type ListPortfoliosByEntryIDRow struct {
	ID        string
	EntryID   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) ListPortfoliosByEntryID(ctx context.Context, entryID string) ([]ListPortfoliosByEntryIDRow, error) {
	rows, err := q.db.Query(ctx, listPortfoliosByEntryID, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPortfoliosByEntryIDRow
	for rows.Next() {
		var i ListPortfoliosByEntryIDRow
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePortfolio = `-- name: UpdatePortfolio :execrows
UPDATE calcutta_portfolios
SET maximum_points = $1,
    updated_at = $2
WHERE id = $3 AND deleted_at IS NULL
`

type UpdatePortfolioParams struct {
	MaximumPoints pgtype.Numeric
	UpdatedAt     pgtype.Timestamptz
	ID            string
}

func (q *Queries) UpdatePortfolio(ctx context.Context, arg UpdatePortfolioParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePortfolio, arg.MaximumPoints, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
