// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: calcuttas.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCalcutta = `-- name: CreateCalcutta :exec
INSERT INTO calcuttas (id, tournament_id, owner_id, name, min_teams, max_teams, max_bid, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateCalcuttaParams struct {
	ID           string
	TournamentID string
	OwnerID      string
	Name         string
	MinTeams     int32
	MaxTeams     int32
	MaxBid       int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) CreateCalcutta(ctx context.Context, arg CreateCalcuttaParams) error {
	_, err := q.db.Exec(ctx, createCalcutta,
		arg.ID,
		arg.TournamentID,
		arg.OwnerID,
		arg.Name,
		arg.MinTeams,
		arg.MaxTeams,
		arg.MaxBid,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteCalcutta = `-- name: DeleteCalcutta :execrows
UPDATE calcuttas
SET deleted_at = $1,
    updated_at = $2
WHERE id = $3 AND deleted_at IS NULL
`

type DeleteCalcuttaParams struct {
	DeletedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	ID        string
}

func (q *Queries) DeleteCalcutta(ctx context.Context, arg DeleteCalcuttaParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCalcutta, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCalcuttaByID = `-- name: GetCalcuttaByID :one
SELECT id, tournament_id, owner_id, name, min_teams, max_teams, max_bid, created_at, updated_at
FROM calcuttas
WHERE id = $1 AND deleted_at IS NULL
`

type GetCalcuttaByIDRow struct {
	ID           string
	TournamentID string
	OwnerID      string
	Name         string
	MinTeams     int32
	MaxTeams     int32
	MaxBid       int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) GetCalcuttaByID(ctx context.Context, id string) (GetCalcuttaByIDRow, error) {
	row := q.db.QueryRow(ctx, getCalcuttaByID, id)
	var i GetCalcuttaByIDRow
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.OwnerID,
		&i.Name,
		&i.MinTeams,
		&i.MaxTeams,
		&i.MaxBid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCalcuttasByTournament = `-- name: GetCalcuttasByTournament :many
SELECT id, tournament_id, owner_id, name, min_teams, max_teams, max_bid, created_at, updated_at, deleted_at
FROM calcuttas
WHERE tournament_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCalcuttasByTournament(ctx context.Context, tournamentID string) ([]Calcutta, error) {
	rows, err := q.db.Query(ctx, getCalcuttasByTournament, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Calcutta
	for rows.Next() {
		var i Calcutta
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.OwnerID,
			&i.Name,
			&i.MinTeams,
			&i.MaxTeams,
			&i.MaxBid,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCalcuttas = `-- name: ListCalcuttas :many
SELECT id, tournament_id, owner_id, name, min_teams, max_teams, max_bid, created_at, updated_at
FROM calcuttas
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

type ListCalcuttasRow struct {
	ID           string
	TournamentID string
	OwnerID      string
	Name         string
	MinTeams     int32
	MaxTeams     int32
	MaxBid       int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) ListCalcuttas(ctx context.Context) ([]ListCalcuttasRow, error) {
	rows, err := q.db.Query(ctx, listCalcuttas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCalcuttasRow
	for rows.Next() {
		var i ListCalcuttasRow
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.OwnerID,
			&i.Name,
			&i.MinTeams,
			&i.MaxTeams,
			&i.MaxBid,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCalcutta = `-- name: UpdateCalcutta :execrows
UPDATE calcuttas
SET tournament_id = $1,
    owner_id = $2,
    name = $3,
    min_teams = $4,
    max_teams = $5,
    max_bid = $6,
    updated_at = $7
WHERE id = $8 AND deleted_at IS NULL
`

type UpdateCalcuttaParams struct {
	TournamentID string
	OwnerID      string
	Name         string
	MinTeams     int32
	MaxTeams     int32
	MaxBid       int32
	UpdatedAt    pgtype.Timestamptz
	ID           string
}

func (q *Queries) UpdateCalcutta(ctx context.Context, arg UpdateCalcuttaParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCalcutta,
		arg.TournamentID,
		arg.OwnerID,
		arg.Name,
		arg.MinTeams,
		arg.MaxTeams,
		arg.MaxBid,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
