// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: calcutta_rounds.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCalcuttaRound = `-- name: CreateCalcuttaRound :exec
INSERT INTO core.calcutta_scoring_rules (id, calcutta_id, win_index, points_awarded, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateCalcuttaRoundParams struct {
	ID            string
	CalcuttaID    string
	WinIndex      int32
	PointsAwarded int32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) CreateCalcuttaRound(ctx context.Context, arg CreateCalcuttaRoundParams) error {
	_, err := q.db.Exec(ctx, createCalcuttaRound,
		arg.ID,
		arg.CalcuttaID,
		arg.WinIndex,
		arg.PointsAwarded,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listCalcuttaRounds = `-- name: ListCalcuttaRounds :many
SELECT
    id,
    calcutta_id,
    win_index AS round,
    points_awarded AS points,
    created_at,
    updated_at
FROM core.calcutta_scoring_rules
WHERE calcutta_id = $1 AND deleted_at IS NULL
ORDER BY win_index ASC
`

type ListCalcuttaRoundsRow struct {
	ID         string
	CalcuttaID string
	Round      int32
	Points     int32
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) ListCalcuttaRounds(ctx context.Context, calcuttaID string) ([]ListCalcuttaRoundsRow, error) {
	rows, err := q.db.Query(ctx, listCalcuttaRounds, calcuttaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCalcuttaRoundsRow
	for rows.Next() {
		var i ListCalcuttaRoundsRow
		if err := rows.Scan(
			&i.ID,
			&i.CalcuttaID,
			&i.Round,
			&i.Points,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
