// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: calcutta_portfolio_teams.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPortfolioTeam = `-- name: CreatePortfolioTeam :exec
INSERT INTO calcutta_portfolio_teams (
    id,
    portfolio_id,
    team_id,
    ownership_percentage,
    actual_points,
    expected_points,
    predicted_points,
    created_at,
    updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreatePortfolioTeamParams struct {
	ID                  string
	PortfolioID         string
	TeamID              string
	OwnershipPercentage pgtype.Numeric
	ActualPoints        pgtype.Numeric
	ExpectedPoints      pgtype.Numeric
	PredictedPoints     pgtype.Numeric
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

func (q *Queries) CreatePortfolioTeam(ctx context.Context, arg CreatePortfolioTeamParams) error {
	_, err := q.db.Exec(ctx, createPortfolioTeam,
		arg.ID,
		arg.PortfolioID,
		arg.TeamID,
		arg.OwnershipPercentage,
		arg.ActualPoints,
		arg.ExpectedPoints,
		arg.PredictedPoints,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listPortfolioTeamsByPortfolioID = `-- name: ListPortfolioTeamsByPortfolioID :many
SELECT
    cpt.id,
    cpt.portfolio_id,
    cpt.team_id,
    cpt.ownership_percentage::float8 AS ownership_percentage,
    cpt.actual_points::float8 AS actual_points,
    cpt.expected_points::float8 AS expected_points,
    cpt.predicted_points::float8 AS predicted_points,
    cpt.created_at,
    cpt.updated_at,
    cpt.deleted_at,
    tt.id AS tournament_team_id,
    tt.school_id,
    tt.tournament_id,
    tt.seed,
    tt.region,
    tt.byes,
    tt.wins,
    tt.eliminated,
    tt.created_at AS team_created_at,
    tt.updated_at AS team_updated_at,
    s.name AS school_name
FROM calcutta_portfolio_teams cpt
JOIN tournament_teams tt ON cpt.team_id = tt.id
LEFT JOIN schools s ON tt.school_id = s.id
WHERE cpt.portfolio_id = $1 AND cpt.deleted_at IS NULL
`

type ListPortfolioTeamsByPortfolioIDRow struct {
	ID                  string
	PortfolioID         string
	TeamID              string
	OwnershipPercentage float64
	ActualPoints        float64
	ExpectedPoints      float64
	PredictedPoints     float64
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	DeletedAt           pgtype.Timestamptz
	TournamentTeamID    string
	SchoolID            string
	TournamentID        string
	Seed                int32
	Region              string
	Byes                int32
	Wins                int32
	Eliminated          bool
	TeamCreatedAt       pgtype.Timestamptz
	TeamUpdatedAt       pgtype.Timestamptz
	SchoolName          *string
}

func (q *Queries) ListPortfolioTeamsByPortfolioID(ctx context.Context, portfolioID string) ([]ListPortfolioTeamsByPortfolioIDRow, error) {
	rows, err := q.db.Query(ctx, listPortfolioTeamsByPortfolioID, portfolioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPortfolioTeamsByPortfolioIDRow
	for rows.Next() {
		var i ListPortfolioTeamsByPortfolioIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PortfolioID,
			&i.TeamID,
			&i.OwnershipPercentage,
			&i.ActualPoints,
			&i.ExpectedPoints,
			&i.PredictedPoints,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TournamentTeamID,
			&i.SchoolID,
			&i.TournamentID,
			&i.Seed,
			&i.Region,
			&i.Byes,
			&i.Wins,
			&i.Eliminated,
			&i.TeamCreatedAt,
			&i.TeamUpdatedAt,
			&i.SchoolName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePortfolioTeam = `-- name: UpdatePortfolioTeam :execrows
UPDATE calcutta_portfolio_teams
SET ownership_percentage = $1,
    actual_points = $2,
    expected_points = $3,
    predicted_points = $4,
    updated_at = $5
WHERE id = $6 AND deleted_at IS NULL
`

type UpdatePortfolioTeamParams struct {
	OwnershipPercentage pgtype.Numeric
	ActualPoints        pgtype.Numeric
	ExpectedPoints      pgtype.Numeric
	PredictedPoints     pgtype.Numeric
	UpdatedAt           pgtype.Timestamptz
	ID                  string
}

func (q *Queries) UpdatePortfolioTeam(ctx context.Context, arg UpdatePortfolioTeamParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePortfolioTeam,
		arg.OwnershipPercentage,
		arg.ActualPoints,
		arg.ExpectedPoints,
		arg.PredictedPoints,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
