// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: calcutta_payouts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listCalcuttaPayouts = `-- name: ListCalcuttaPayouts :many
SELECT id, calcutta_id, position, amount_cents, created_at, updated_at
FROM core.payouts
WHERE calcutta_id = $1 AND deleted_at IS NULL
ORDER BY position ASC
`

type ListCalcuttaPayoutsRow struct {
	ID          string
	CalcuttaID  string
	Position    int32
	AmountCents int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) ListCalcuttaPayouts(ctx context.Context, calcuttaID string) ([]ListCalcuttaPayoutsRow, error) {
	rows, err := q.db.Query(ctx, listCalcuttaPayouts, calcuttaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCalcuttaPayoutsRow
	for rows.Next() {
		var i ListCalcuttaPayoutsRow
		if err := rows.Scan(
			&i.ID,
			&i.CalcuttaID,
			&i.Position,
			&i.AmountCents,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
