// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: calcutta_entries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEntryByID = `-- name: GetEntryByID :one
SELECT
    id,
    name,
    user_id,
    calcutta_id,
    created_at,
    updated_at,
    deleted_at
FROM calcutta_entries
WHERE id = $1 AND deleted_at IS NULL
`

type GetEntryByIDRow struct {
	ID         string
	Name       string
	UserID     pgtype.UUID
	CalcuttaID string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
}

func (q *Queries) GetEntryByID(ctx context.Context, id string) (GetEntryByIDRow, error) {
	row := q.db.QueryRow(ctx, getEntryByID, id)
	var i GetEntryByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.CalcuttaID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listEntriesByCalcuttaID = `-- name: ListEntriesByCalcuttaID :many
WITH entry_points AS (
    SELECT
        cp.entry_id,
        COALESCE(SUM(cpt.actual_points), 0)::float8 AS total_points
    FROM calcutta_portfolios cp
    LEFT JOIN calcutta_portfolio_teams cpt ON cp.id = cpt.portfolio_id
    WHERE cp.deleted_at IS NULL AND cpt.deleted_at IS NULL
    GROUP BY cp.entry_id
)
SELECT
    ce.id,
    ce.name,
    ce.user_id,
    ce.calcutta_id,
    ce.created_at,
    ce.updated_at,
    ce.deleted_at,
    COALESCE(ep.total_points, 0)::float8 AS total_points
FROM calcutta_entries ce
LEFT JOIN entry_points ep ON ce.id = ep.entry_id
WHERE ce.calcutta_id = $1 AND ce.deleted_at IS NULL
ORDER BY ep.total_points DESC NULLS LAST, ce.created_at DESC
`

type ListEntriesByCalcuttaIDRow struct {
	ID          string
	Name        string
	UserID      pgtype.UUID
	CalcuttaID  string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	TotalPoints float64
}

func (q *Queries) ListEntriesByCalcuttaID(ctx context.Context, calcuttaID string) ([]ListEntriesByCalcuttaIDRow, error) {
	rows, err := q.db.Query(ctx, listEntriesByCalcuttaID, calcuttaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntriesByCalcuttaIDRow
	for rows.Next() {
		var i ListEntriesByCalcuttaIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.CalcuttaID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TotalPoints,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
