// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForBulkCreatePredictedTeamValues implements pgx.CopyFromSource.
type iteratorForBulkCreatePredictedTeamValues struct {
	rows                 []BulkCreatePredictedTeamValuesParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkCreatePredictedTeamValues) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkCreatePredictedTeamValues) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].PredictionBatchID,
		r.rows[0].TournamentID,
		r.rows[0].TeamID,
		r.rows[0].ExpectedPoints,
		r.rows[0].VariancePoints,
		r.rows[0].StdPoints,
		r.rows[0].PRound1,
		r.rows[0].PRound2,
		r.rows[0].PRound3,
		r.rows[0].PRound4,
		r.rows[0].PRound5,
		r.rows[0].PRound6,
		r.rows[0].PRound7,
	}, nil
}

func (r iteratorForBulkCreatePredictedTeamValues) Err() error {
	return nil
}

func (q *Queries) BulkCreatePredictedTeamValues(ctx context.Context, arg []BulkCreatePredictedTeamValuesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"compute", "predicted_team_values"}, []string{"prediction_batch_id", "tournament_id", "team_id", "expected_points", "variance_points", "std_points", "p_round_1", "p_round_2", "p_round_3", "p_round_4", "p_round_5", "p_round_6", "p_round_7"}, &iteratorForBulkCreatePredictedTeamValues{rows: arg})
}
