// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: investment_snapshots.sql

package sqlc

import (
	"context"
)

const createInvestmentSnapshot = `-- name: CreateInvestmentSnapshot :exec
INSERT INTO core.investment_snapshots (portfolio_id, changed_by, reason, investments)
VALUES ($1, $2, $3, $4)
`

type CreateInvestmentSnapshotParams struct {
	PortfolioID string
	ChangedBy   string
	Reason      string
	Investments []byte
}

func (q *Queries) CreateInvestmentSnapshot(ctx context.Context, arg CreateInvestmentSnapshotParams) error {
	_, err := q.db.Exec(ctx, createInvestmentSnapshot,
		arg.PortfolioID,
		arg.ChangedBy,
		arg.Reason,
		arg.Investments,
	)
	return err
}
