// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ml_analytics_portfolios.sql

package sqlc

import (
	"context"
)

const getActualEntryPortfolio = `-- name: GetActualEntryPortfolio :many
WITH strategy_run AS (
	SELECT sgr.calcutta_id
	FROM derived.strategy_generation_runs sgr
	WHERE sgr.run_key = $2::text
		AND sgr.deleted_at IS NULL
	LIMIT 1
)
SELECT 
    t.id as team_id,
    s.name as school_name,
    t.seed,
    t.region,
    eb.bid_points
FROM derived.entry_bids eb
JOIN strategy_run sr ON sr.calcutta_id = eb.calcutta_id
JOIN core.teams t ON eb.team_id = t.id AND t.deleted_at IS NULL
JOIN core.schools s ON s.id = t.school_id AND s.deleted_at IS NULL
WHERE eb.entry_name = $1
    AND eb.deleted_at IS NULL
ORDER BY eb.bid_points DESC
`

type GetActualEntryPortfolioParams struct {
	EntryName string
	RunID     string
}

type GetActualEntryPortfolioRow struct {
	TeamID     string
	SchoolName string
	Seed       int32
	Region     string
	BidPoints  int32
}

// For actual entries from the auction
func (q *Queries) GetActualEntryPortfolio(ctx context.Context, arg GetActualEntryPortfolioParams) ([]GetActualEntryPortfolioRow, error) {
	rows, err := q.db.Query(ctx, getActualEntryPortfolio, arg.EntryName, arg.RunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActualEntryPortfolioRow
	for rows.Next() {
		var i GetActualEntryPortfolioRow
		if err := rows.Scan(
			&i.TeamID,
			&i.SchoolName,
			&i.Seed,
			&i.Region,
			&i.BidPoints,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntryPortfolio = `-- name: GetEntryPortfolio :many
SELECT 
    t.id as team_id,
    s.name as school_name,
    t.seed,
    t.region,
    reb.bid_points as bid_points
FROM derived.recommended_entry_bids reb
JOIN core.teams t ON reb.team_id = t.id AND t.deleted_at IS NULL
JOIN core.schools s ON s.id = t.school_id AND s.deleted_at IS NULL
WHERE reb.run_id = $1
    AND reb.deleted_at IS NULL
ORDER BY reb.bid_points DESC
`

type GetEntryPortfolioRow struct {
	TeamID     string
	SchoolName string
	Seed       int32
	Region     string
	BidPoints  int32
}

// For our strategy entry
func (q *Queries) GetEntryPortfolio(ctx context.Context, runID string) ([]GetEntryPortfolioRow, error) {
	rows, err := q.db.Query(ctx, getEntryPortfolio, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEntryPortfolioRow
	for rows.Next() {
		var i GetEntryPortfolioRow
		if err := rows.Scan(
			&i.TeamID,
			&i.SchoolName,
			&i.Seed,
			&i.Region,
			&i.BidPoints,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntryPortfolioByStrategyGenerationRunID = `-- name: GetEntryPortfolioByStrategyGenerationRunID :many
SELECT
	t.id as team_id,
	s.name as school_name,
	t.seed,
	t.region,
	reb.bid_points as bid_points
FROM derived.recommended_entry_bids reb
JOIN core.teams t ON reb.team_id = t.id AND t.deleted_at IS NULL
JOIN core.schools s ON s.id = t.school_id AND s.deleted_at IS NULL
WHERE reb.strategy_generation_run_id = $1::uuid
    AND reb.deleted_at IS NULL
ORDER BY reb.bid_points DESC
`

type GetEntryPortfolioByStrategyGenerationRunIDRow struct {
	TeamID     string
	SchoolName string
	Seed       int32
	Region     string
	BidPoints  int32
}

// For our strategy entry (lineage-native)
func (q *Queries) GetEntryPortfolioByStrategyGenerationRunID(ctx context.Context, strategyGenerationRunID string) ([]GetEntryPortfolioByStrategyGenerationRunIDRow, error) {
	rows, err := q.db.Query(ctx, getEntryPortfolioByStrategyGenerationRunID, strategyGenerationRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEntryPortfolioByStrategyGenerationRunIDRow
	for rows.Next() {
		var i GetEntryPortfolioByStrategyGenerationRunIDRow
		if err := rows.Scan(
			&i.TeamID,
			&i.SchoolName,
			&i.Seed,
			&i.Region,
			&i.BidPoints,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOurEntryBidsByRunID = `-- name: GetOurEntryBidsByRunID :many
SELECT 
    t.id as team_id,
    s.name as school_name,
    t.seed,
    t.region,
    reb.bid_points,
    reb.expected_roi
FROM derived.recommended_entry_bids reb
JOIN core.teams t ON t.id = reb.team_id AND t.deleted_at IS NULL
JOIN core.schools s ON s.id = t.school_id AND s.deleted_at IS NULL
WHERE reb.run_id = $1::text
    AND reb.deleted_at IS NULL
ORDER BY reb.bid_points DESC
`

type GetOurEntryBidsByRunIDRow struct {
	TeamID      string
	SchoolName  string
	Seed        int32
	Region      string
	BidPoints   int32
	ExpectedRoi float64
}

func (q *Queries) GetOurEntryBidsByRunID(ctx context.Context, dollar_1 string) ([]GetOurEntryBidsByRunIDRow, error) {
	rows, err := q.db.Query(ctx, getOurEntryBidsByRunID, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOurEntryBidsByRunIDRow
	for rows.Next() {
		var i GetOurEntryBidsByRunIDRow
		if err := rows.Scan(
			&i.TeamID,
			&i.SchoolName,
			&i.Seed,
			&i.Region,
			&i.BidPoints,
			&i.ExpectedRoi,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOurEntryBidsByStrategyGenerationRunID = `-- name: GetOurEntryBidsByStrategyGenerationRunID :many
SELECT
	t.id as team_id,
	s.name as school_name,
	t.seed,
	t.region,
	reb.bid_points,
	reb.expected_roi
FROM derived.recommended_entry_bids reb
JOIN core.teams t ON t.id = reb.team_id AND t.deleted_at IS NULL
JOIN core.schools s ON s.id = t.school_id AND s.deleted_at IS NULL
WHERE reb.strategy_generation_run_id = $1::uuid
    AND reb.deleted_at IS NULL
ORDER BY reb.bid_points DESC
`

type GetOurEntryBidsByStrategyGenerationRunIDRow struct {
	TeamID      string
	SchoolName  string
	Seed        int32
	Region      string
	BidPoints   int32
	ExpectedRoi float64
}

func (q *Queries) GetOurEntryBidsByStrategyGenerationRunID(ctx context.Context, dollar_1 string) ([]GetOurEntryBidsByStrategyGenerationRunIDRow, error) {
	rows, err := q.db.Query(ctx, getOurEntryBidsByStrategyGenerationRunID, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOurEntryBidsByStrategyGenerationRunIDRow
	for rows.Next() {
		var i GetOurEntryBidsByStrategyGenerationRunIDRow
		if err := rows.Scan(
			&i.TeamID,
			&i.SchoolName,
			&i.Seed,
			&i.Region,
			&i.BidPoints,
			&i.ExpectedRoi,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
