// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ml_analytics_runs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getStrategyGenerationRunByRunKey = `-- name: GetStrategyGenerationRunByRunKey :one
SELECT
	sgr.id,
	COALESCE(sgr.run_key, ''::text) AS run_id,
	COALESCE(NULLIF(sgr.name, ''::text), COALESCE(sgr.run_key, ''::text)) AS name,
	sgr.calcutta_id,
	COALESCE(NULLIF(sgr.optimizer_key::text, ''::text), 'legacy'::text) AS strategy,
	COALESCE(tsb.n_sims, 0)::int AS n_sims,
	COALESCE(tsb.seed, 0)::int AS seed,
	COALESCE(c.budget_points, 100)::int AS budget_points,
	sgr.created_at
FROM derived.strategy_generation_runs sgr
LEFT JOIN core.calcuttas c
	ON c.id = sgr.calcutta_id
	AND c.deleted_at IS NULL
LEFT JOIN derived.simulated_tournaments tsb
	ON tsb.id = sgr.simulated_tournament_id
	AND tsb.deleted_at IS NULL
WHERE sgr.run_key = $1::text
	AND sgr.deleted_at IS NULL
LIMIT 1
`

type GetStrategyGenerationRunByRunKeyRow struct {
	ID           string
	RunID        *string
	Name         interface{}
	CalcuttaID   pgtype.UUID
	Strategy     interface{}
	NSims        int32
	Seed         int32
	BudgetPoints int32
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) GetStrategyGenerationRunByRunKey(ctx context.Context, dollar_1 string) (GetStrategyGenerationRunByRunKeyRow, error) {
	row := q.db.QueryRow(ctx, getStrategyGenerationRunByRunKey, dollar_1)
	var i GetStrategyGenerationRunByRunKeyRow
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Name,
		&i.CalcuttaID,
		&i.Strategy,
		&i.NSims,
		&i.Seed,
		&i.BudgetPoints,
		&i.CreatedAt,
	)
	return i, err
}

const listCalcuttaEvaluationRunsByCoreCalcuttaID = `-- name: ListCalcuttaEvaluationRunsByCoreCalcuttaID :many
SELECT
	cer.id,
	cer.simulated_tournament_id,
	cer.calcutta_snapshot_id,
	cer.purpose,
	cer.created_at
FROM derived.calcutta_evaluation_runs cer
JOIN core.calcutta_snapshots cs
	ON cs.id = cer.calcutta_snapshot_id
	AND cs.deleted_at IS NULL
WHERE cs.base_calcutta_id = $1::uuid
	AND cer.deleted_at IS NULL
ORDER BY cer.created_at DESC
`

type ListCalcuttaEvaluationRunsByCoreCalcuttaIDRow struct {
	ID                    string
	SimulatedTournamentID string
	CalcuttaSnapshotID    pgtype.UUID
	Purpose               string
	CreatedAt             pgtype.Timestamptz
}

func (q *Queries) ListCalcuttaEvaluationRunsByCoreCalcuttaID(ctx context.Context, dollar_1 string) ([]ListCalcuttaEvaluationRunsByCoreCalcuttaIDRow, error) {
	rows, err := q.db.Query(ctx, listCalcuttaEvaluationRunsByCoreCalcuttaID, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCalcuttaEvaluationRunsByCoreCalcuttaIDRow
	for rows.Next() {
		var i ListCalcuttaEvaluationRunsByCoreCalcuttaIDRow
		if err := rows.Scan(
			&i.ID,
			&i.SimulatedTournamentID,
			&i.CalcuttaSnapshotID,
			&i.Purpose,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStrategyGenerationRunsByCoreCalcuttaID = `-- name: ListStrategyGenerationRunsByCoreCalcuttaID :many
SELECT
	sgr.id,
	sgr.run_key,
	sgr.simulated_tournament_id,
	sgr.calcutta_id,
	sgr.purpose,
	sgr.returns_model_key,
	sgr.investment_model_key,
	sgr.optimizer_key,
	sgr.params_json,
	sgr.git_sha,
	sgr.created_at
FROM derived.strategy_generation_runs sgr
WHERE sgr.calcutta_id = $1::uuid
	AND sgr.deleted_at IS NULL
ORDER BY sgr.created_at DESC
`

type ListStrategyGenerationRunsByCoreCalcuttaIDRow struct {
	ID                    string
	RunKey                *string
	SimulatedTournamentID pgtype.UUID
	CalcuttaID            pgtype.UUID
	Purpose               string
	ReturnsModelKey       string
	InvestmentModelKey    string
	OptimizerKey          string
	ParamsJson            []byte
	GitSha                *string
	CreatedAt             pgtype.Timestamptz
}

func (q *Queries) ListStrategyGenerationRunsByCoreCalcuttaID(ctx context.Context, dollar_1 string) ([]ListStrategyGenerationRunsByCoreCalcuttaIDRow, error) {
	rows, err := q.db.Query(ctx, listStrategyGenerationRunsByCoreCalcuttaID, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStrategyGenerationRunsByCoreCalcuttaIDRow
	for rows.Next() {
		var i ListStrategyGenerationRunsByCoreCalcuttaIDRow
		if err := rows.Scan(
			&i.ID,
			&i.RunKey,
			&i.SimulatedTournamentID,
			&i.CalcuttaID,
			&i.Purpose,
			&i.ReturnsModelKey,
			&i.InvestmentModelKey,
			&i.OptimizerKey,
			&i.ParamsJson,
			&i.GitSha,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
