// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ml_analytics.sql

package sqlc

import (
	"context"
)

const mlAnalyticsNoop = `-- name: MlAnalyticsNoop :one

SELECT 1::int as ok
`

// ML Analytics Queries
// For tournament simulation and entry evaluation data
func (q *Queries) MlAnalyticsNoop(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, mlAnalyticsNoop)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}
