// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthSession struct {
	ID               string
	UserID           string
	RefreshTokenHash string
	ExpiresAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
	LastUsedAt       pgtype.Timestamptz
	UserAgent        *string
	IpAddress        *string
}

type Calcutta struct {
	ID           string
	TournamentID string
	OwnerID      string
	Name         string
	MinTeams     int32
	MaxTeams     int32
	MaxBid       int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type CalcuttaEntry struct {
	ID         string
	Name       string
	UserID     pgtype.UUID
	CalcuttaID string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
}

type CalcuttaEntryTeam struct {
	ID        string
	EntryID   string
	TeamID    string
	Bid       int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type CalcuttaPayout struct {
	ID          string
	CalcuttaID  string
	Position    int32
	AmountCents int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type CalcuttaPortfolio struct {
	ID            string
	EntryID       string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
	MaximumPoints pgtype.Numeric
}

type CalcuttaPortfolioTeam struct {
	ID                  string
	PortfolioID         string
	TeamID              string
	OwnershipPercentage pgtype.Numeric
	ActualPoints        pgtype.Numeric
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	DeletedAt           pgtype.Timestamptz
	ExpectedPoints      pgtype.Numeric
	PredictedPoints     pgtype.Numeric
}

type CalcuttaRound struct {
	ID         string
	CalcuttaID string
	Round      int32
	Points     int32
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
}

type Grant struct {
	ID           string
	UserID       string
	ScopeType    string
	ScopeID      pgtype.UUID
	LabelID      pgtype.UUID
	PermissionID pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
	RevokedAt    pgtype.Timestamptz
}

type Label struct {
	ID          string
	Key         string
	Description *string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type LabelPermission struct {
	LabelID      string
	PermissionID string
	CreatedAt    pgtype.Timestamptz
}

type Permission struct {
	ID          string
	Key         string
	Description *string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type School struct {
	ID        string
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type Tournament struct {
	ID                   string
	Name                 string
	Rounds               int32
	StartingAt           *pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	DeletedAt            pgtype.Timestamptz
	FinalFourTopLeft     *string
	FinalFourBottomLeft  *string
	FinalFourTopRight    *string
	FinalFourBottomRight *string
}

type TournamentGame struct {
	ID           string
	TournamentID string
	Team1ID      pgtype.UUID
	Team2ID      pgtype.UUID
	TipoffTime   pgtype.Timestamptz
	SortOrder    int32
	Team1Score   *int32
	Team2Score   *int32
	NextGameID   pgtype.UUID
	NextGameSlot *int32
	IsFinal      bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type TournamentTeam struct {
	ID           string
	TournamentID string
	SchoolID     string
	Seed         int32
	Region       string
	Byes         int32
	Wins         int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	Eliminated   bool
}

type TournamentTeamKenpomStat struct {
	TournamentTeamID string
	NetRtg           *float64
	ORtg             *float64
	DRtg             *float64
	AdjT             *float64
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}

type User struct {
	ID           string
	Email        string
	FirstName    string
	LastName     string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	PasswordHash *string
}
