// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ComputeGameOutcomeRun struct {
	ID           string
	TournamentID string
	ParamsJson   []byte
	GitSha       *string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	RunKey       string
}

type ComputePredictedGameOutcome struct {
	ID           string
	TournamentID string
	GameID       string
	Round        int32
	Team1ID      string
	Team2ID      string
	PTeam1Wins   float64
	PMatchup     float64
	ModelVersion *string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	RunID        pgtype.UUID
}

// Stores predicted expected points and round probabilities for each team (analogous to simulated_teams for simulations)
type ComputePredictedTeamValue struct {
	ID                string
	PredictionBatchID string
	TournamentID      string
	TeamID            string
	// Expected tournament points for 100% ownership of this team
	ExpectedPoints float64
	VariancePoints *float64
	StdPoints      *float64
	// Probability of winning first game (First Four or Round of 64)
	PRound1 *float64
	// Probability of reaching Round of 32
	PRound2 *float64
	// Probability of reaching Sweet 16
	PRound3 *float64
	// Probability of reaching Elite 8
	PRound4 *float64
	// Probability of reaching Final Four
	PRound5 *float64
	// Probability of reaching Championship game
	PRound6 *float64
	// Probability of winning Championship
	PRound7              *float64
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	DeletedAt            pgtype.Timestamptz
	FavoritesTotalPoints *float64
	ActualPoints         *float64
}

// Stores metadata for prediction generation runs (analogous to simulated_tournaments for simulations)
type ComputePredictionBatch struct {
	ID           string
	TournamentID string
	// Identifier for the probability model used (e.g., kenpom)
	ProbabilitySourceKey string
	// Parameters for the game outcome model (e.g., {"kind": "kenpom", "sigma": 10.0})
	GameOutcomeSpecJson []byte
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	DeletedAt           pgtype.Timestamptz
	ThroughRound        int32
}

type ComputeSimulatedTeam struct {
	ID                    string
	TournamentID          string
	SimID                 int32
	TeamID                string
	Wins                  int32
	Byes                  int32
	IsEliminated          bool
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	DeletedAt             pgtype.Timestamptz
	SimulatedTournamentID pgtype.UUID
}

type ComputeSimulatedTournament struct {
	ID                   string
	TournamentID         string
	TournamentSnapshotID string
	NSims                int32
	Seed                 int32
	ProbabilitySourceKey string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	DeletedAt            pgtype.Timestamptz
}

type ComputeTournamentSnapshot struct {
	ID           string
	TournamentID string
	Source       string
	Description  *string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type ComputeTournamentSnapshotTeam struct {
	ID                   string
	TournamentSnapshotID string
	TeamID               string
	Wins                 int32
	Byes                 int32
	IsEliminated         bool
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	DeletedAt            pgtype.Timestamptz
}

type CoreApiKey struct {
	ID         string
	UserID     string
	KeyHash    string
	Label      *string
	CreatedAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
}

type CoreAuthSession struct {
	ID               string
	UserID           string
	RefreshTokenHash string
	ExpiresAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
	LastUsedAt       pgtype.Timestamptz
	UserAgent        *string
	IpAddress        *string
	DeletedAt        pgtype.Timestamptz
}

type CoreCompetition struct {
	ID        string
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type CoreGrant struct {
	ID           string
	UserID       string
	ScopeType    string
	ScopeID      pgtype.UUID
	RoleID       pgtype.UUID
	PermissionID pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
	RevokedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	GrantedBy    pgtype.UUID
}

type CoreIdempotencyKey struct {
	Key            string
	UserID         string
	CreatedAt      pgtype.Timestamptz
	ResponseStatus *int32
	ResponseBody   []byte
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type CoreInvestment struct {
	ID          string
	PortfolioID string
	TeamID      string
	Credits     int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type CorePayout struct {
	ID          string
	PoolID      string
	Position    int32
	AmountCents int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type CorePermission struct {
	ID          string
	Key         string
	Description *string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type CorePool struct {
	ID                   string
	TournamentID         string
	OwnerID              string
	Name                 string
	MinTeams             int32
	MaxTeams             int32
	MaxInvestmentCredits int32
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	DeletedAt            pgtype.Timestamptz
	BudgetCredits        int32
	Visibility           string
	CreatedBy            string
	EntryFeeCents        int32
}

type CorePoolInvitation struct {
	ID        string
	PoolID    string
	UserID    string
	InvitedBy string
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

type CorePoolScoringRule struct {
	ID            string
	PoolID        string
	WinIndex      int32
	PointsAwarded int32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

type CorePortfolio struct {
	ID        string
	Name      string
	UserID    pgtype.UUID
	PoolID    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	Status    string
}

type CoreRole struct {
	ID          string
	Key         string
	Description *string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type CoreRolePermission struct {
	RoleID       string
	PermissionID string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type CoreSchool struct {
	ID        string
	Name      string
	Slug      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	ShortName *string
}

type CoreSeason struct {
	ID        string
	Year      int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type CoreTeam struct {
	ID           string
	TournamentID string
	SchoolID     string
	Seed         int32
	Region       string
	Byes         int32
	Wins         int32
	IsEliminated bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type CoreTeamKenpomStat struct {
	TeamID    string
	NetRtg    *float64
	ORtg      *float64
	DRtg      *float64
	AdjT      *float64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type CoreTournament struct {
	ID                   string
	CompetitionID        string
	SeasonID             string
	ImportKey            string
	Rounds               int32
	StartingAt           pgtype.Timestamptz
	FinalFourTopLeft     *string
	FinalFourBottomLeft  *string
	FinalFourTopRight    *string
	FinalFourBottomRight *string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	DeletedAt            pgtype.Timestamptz
}

type CoreTournamentImport struct {
	ID           string
	Filename     string
	Sha256       string
	SizeBytes    int64
	Archive      []byte
	ImportReport []byte
	VerifyReport []byte
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	Status       string
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
	ErrorMessage *string
}

type CoreUser struct {
	ID                 string
	Email              *string
	FirstName          string
	LastName           string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
	PasswordHash       *string
	Status             string
	InviteTokenHash    *string
	InviteExpiresAt    pgtype.Timestamptz
	InviteConsumedAt   pgtype.Timestamptz
	InvitedAt          pgtype.Timestamptz
	LastInviteSentAt   pgtype.Timestamptz
	ExternalProvider   *string
	ExternalProviderID *string
	InvitedBy          pgtype.UUID
	ResetTokenHash     *string
	ResetExpiresAt     pgtype.Timestamptz
	ResetConsumedAt    pgtype.Timestamptz
	LastResetSentAt    pgtype.Timestamptz
}

type CoreUserMerge struct {
	ID               string
	SourceUserID     string
	TargetUserID     string
	MergedBy         string
	EntriesMoved     int32
	InvitationsMoved int32
	GrantsMoved      int32
	CreatedAt        pgtype.Timestamptz
}

type DerivedOwnershipDetail struct {
	ID                  interface{}
	PortfolioID         string
	TeamID              string
	OwnershipPercentage float64
	ActualReturns       int32
	ExpectedReturns     int32
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           interface{}
	DeletedAt           pgtype.Timestamptz
}

type DerivedOwnershipSummary struct {
	ID             string
	PortfolioID    string
	MaximumReturns int64
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      interface{}
	DeletedAt      pgtype.Timestamptz
}

type DerivedRunJob struct {
	ID                string
	RunKind           string
	RunID             string
	RunKey            string
	Status            string
	Attempt           int32
	ParamsJson        []byte
	ProgressJson      []byte
	ProgressUpdatedAt pgtype.Timestamptz
	ClaimedAt         pgtype.Timestamptz
	ClaimedBy         *string
	StartedAt         pgtype.Timestamptz
	FinishedAt        pgtype.Timestamptz
	ErrorMessage      *string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	Priority          int16
	DedupKey          *string
	RetryAfter        pgtype.Timestamptz
}

type LabEntry struct {
	ID                    string
	InvestmentModelID     string
	CalcuttaID            string
	GameOutcomeKind       string
	GameOutcomeParamsJson []byte
	OptimizerKind         string
	OptimizerParamsJson   []byte
	StartingStateKey      string
	// Optimized bids: [{team_id, bid_points, expected_roi}]. Our optimal allocation given predictions.
	BidsJson  []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	// Market predictions: [{team_id, predicted_market_share, expected_points}]. What model predicts others will bid.
	PredictionsJson []byte
}

type LabEvaluation struct {
	ID                     string
	EntryID                string
	NSims                  int32
	Seed                   int32
	MeanNormalizedPayout   *float64
	MedianNormalizedPayout *float64
	PTop1                  *float64
	PInMoney               *float64
	OurRank                *int32
	SummaryJson            []byte
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	DeletedAt              pgtype.Timestamptz
}

type LabEvaluationEntryResult struct {
	ID                   string
	EvaluationID         string
	EntryName            string
	MeanNormalizedPayout *float64
	PTop1                *float64
	PInMoney             *float64
	Rank                 *int32
	CreatedAt            pgtype.Timestamptz
}

type LabInvestmentModel struct {
	ID         string
	Name       string
	Kind       string
	ParamsJson []byte
	Notes      *string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
}

type LabModelLeaderboard struct {
	InvestmentModelID         string
	ModelName                 string
	ModelKind                 string
	NEntries                  int64
	NEntriesWithPredictions   int64
	NEvaluations              int64
	NCalcuttasWithEntries     int64
	NCalcuttasWithEvaluations int64
	AvgMeanPayout             float64
	AvgMedianPayout           float64
	AvgPTop1                  float64
	AvgPInMoney               float64
	FirstEvalAt               interface{}
	LastEvalAt                interface{}
}

type LabPipelineCalcuttaRun struct {
	ID                string
	PipelineRunID     string
	CalcuttaID        string
	EntryID           pgtype.UUID
	Stage             string
	Status            string
	Progress          float64
	ProgressMessage   *string
	PredictionsJobID  pgtype.UUID
	OptimizationJobID pgtype.UUID
	EvaluationJobID   pgtype.UUID
	EvaluationID      pgtype.UUID
	ErrorMessage      *string
	StartedAt         pgtype.Timestamptz
	FinishedAt        pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type LabPipelineRun struct {
	ID                string
	InvestmentModelID string
	TargetCalcuttaIds []string
	BudgetPoints      int32
	OptimizerKind     string
	NSims             int32
	Seed              int32
	ExcludedEntryName *string
	Status            string
	StartedAt         pgtype.Timestamptz
	FinishedAt        pgtype.Timestamptz
	ErrorMessage      *string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}
