// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CoreApiKey struct {
	ID         string
	UserID     string
	KeyHash    string
	Label      *string
	CreatedAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
}

type CoreAuthSession struct {
	ID               string
	UserID           string
	RefreshTokenHash string
	ExpiresAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
	LastUsedAt       pgtype.Timestamptz
	UserAgent        *string
	IpAddress        *string
	DeletedAt        pgtype.Timestamptz
}

type CoreBundleUpload struct {
	ID           string
	Filename     string
	Sha256       string
	SizeBytes    int64
	Archive      []byte
	ImportReport []byte
	VerifyReport []byte
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	Status       string
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
	ErrorMessage *string
}

type CoreCalcutta struct {
	ID              string
	TournamentID    string
	OwnerID         string
	Name            string
	MinTeams        int32
	MaxTeams        int32
	MaxBid          int32
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
	BudgetPoints    int32
	BiddingOpen     bool
	BiddingLockedAt pgtype.Timestamptz
}

type CoreCalcuttaInvitation struct {
	ID         string
	CalcuttaID string
	UserID     string
	InvitedBy  string
	Status     string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
}

type CoreCalcuttaScoringRule struct {
	ID            string
	CalcuttaID    string
	WinIndex      int32
	PointsAwarded int32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

type CoreCalcuttaSnapshot struct {
	ID             string
	BaseCalcuttaID string
	SnapshotType   string
	Description    *string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type CoreCalcuttaSnapshotEntry struct {
	ID                 string
	CalcuttaSnapshotID string
	EntryID            pgtype.UUID
	DisplayName        string
	IsSynthetic        bool
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
}

type CoreCalcuttaSnapshotEntryTeam struct {
	ID                      string
	CalcuttaSnapshotEntryID string
	TeamID                  string
	BidPoints               int32
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	DeletedAt               pgtype.Timestamptz
}

type CoreCalcuttaSnapshotPayout struct {
	ID                 string
	CalcuttaSnapshotID string
	Position           int32
	AmountCents        int32
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
}

type CoreCalcuttaSnapshotScoringRule struct {
	ID                 string
	CalcuttaSnapshotID string
	WinIndex           int32
	PointsAwarded      int32
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
}

type CoreCompetition struct {
	ID        string
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type CoreDerivedPortfolio struct {
	ID            string
	EntryID       string
	MaximumPoints int64
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     interface{}
	DeletedAt     pgtype.Timestamptz
}

type CoreDerivedPortfolioTeam struct {
	ID                  string
	PortfolioID         string
	TeamID              string
	OwnershipPercentage float64
	ActualPoints        int32
	ExpectedPoints      interface{}
	PredictedPoints     interface{}
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           interface{}
	DeletedAt           pgtype.Timestamptz
	TournamentTeamID    string
	SchoolID            string
	TournamentID        string
	Seed                int32
	Region              string
	Byes                int32
	Wins                int32
	Eliminated          bool
	TeamCreatedAt       pgtype.Timestamptz
	TeamUpdatedAt       pgtype.Timestamptz
	SchoolName          *string
}

type CoreEntry struct {
	ID         string
	Name       string
	UserID     pgtype.UUID
	CalcuttaID string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
}

type CoreEntryTeam struct {
	ID        string
	EntryID   string
	TeamID    string
	BidPoints int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type CoreGrant struct {
	ID           string
	UserID       string
	ScopeType    string
	ScopeID      pgtype.UUID
	LabelID      pgtype.UUID
	PermissionID pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
	RevokedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type CoreLabel struct {
	ID          string
	Key         string
	Description *string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type CoreLabelPermission struct {
	LabelID      string
	PermissionID string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type CorePayout struct {
	ID          string
	CalcuttaID  string
	Position    int32
	AmountCents int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type CorePermission struct {
	ID          string
	Key         string
	Description *string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type CoreSchool struct {
	ID        string
	Name      string
	Slug      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type CoreSeason struct {
	ID        string
	Year      int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type CoreTeam struct {
	ID           string
	TournamentID string
	SchoolID     string
	Seed         int32
	Region       string
	Byes         int32
	Wins         int32
	Eliminated   bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type CoreTeamKenpomStat struct {
	TeamID    string
	NetRtg    *float64
	ORtg      *float64
	DRtg      *float64
	AdjT      *float64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type CoreTournament struct {
	ID                   string
	CompetitionID        string
	SeasonID             string
	Name                 string
	ImportKey            string
	Rounds               int32
	StartingAt           pgtype.Timestamptz
	FinalFourTopLeft     *string
	FinalFourBottomLeft  *string
	FinalFourTopRight    *string
	FinalFourBottomRight *string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	DeletedAt            pgtype.Timestamptz
}

type CoreUser struct {
	ID               string
	Email            string
	FirstName        string
	LastName         string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
	PasswordHash     *string
	Status           string
	InviteTokenHash  *string
	InviteExpiresAt  pgtype.Timestamptz
	InviteConsumedAt pgtype.Timestamptz
	InvitedAt        pgtype.Timestamptz
	LastInviteSentAt pgtype.Timestamptz
}

type DerivedCalcutta struct {
	ID               string
	CoreCalcuttaID   string
	TournamentID     string
	CoreTournamentID string
	OwnerID          string
	Name             string
	MinTeams         int32
	MaxTeams         int32
	MaxBid           int32
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}

type DerivedCalcuttaEvaluationRun struct {
	ID                    string
	SimulatedTournamentID string
	CalcuttaSnapshotID    pgtype.UUID
	Purpose               string
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	DeletedAt             pgtype.Timestamptz
	RunKey                string
	ParamsJson            []byte
	GitSha                *string
	SimulatedCalcuttaID   pgtype.UUID
}

type DerivedDetailedInvestmentReport struct {
	ID                      string
	RunID                   string
	TeamID                  string
	ExpectedPoints          float64
	PredictedMarketPoints   float64
	ActualMarketPoints      *float64
	OurBidPoints            *int32
	ExpectedRoi             float64
	OurRoi                  *float64
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	DeletedAt               pgtype.Timestamptz
	StrategyGenerationRunID pgtype.UUID
}

type DerivedEntryBid struct {
	ID         string
	CalcuttaID string
	EntryName  string
	TeamID     string
	BidPoints  int32
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
}

type DerivedEntryPerformance struct {
	ID                      string
	RunID                   string
	EntryName               string
	MeanNormalizedPayout    float64
	MedianNormalizedPayout  float64
	PTop1                   float64
	PInMoney                float64
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	DeletedAt               pgtype.Timestamptz
	CalcuttaEvaluationRunID pgtype.UUID
}

type DerivedEntrySimulationOutcome struct {
	ID                      string
	RunID                   string
	EntryName               string
	SimID                   int32
	PayoutCents             int32
	Rank                    int32
	CreatedAt               pgtype.Timestamptz
	PointsScored            float64
	UpdatedAt               pgtype.Timestamptz
	DeletedAt               pgtype.Timestamptz
	CalcuttaEvaluationRunID pgtype.UUID
}

type DerivedGameOutcomeRun struct {
	ID                string
	AlgorithmID       string
	TournamentID      string
	ParamsJson        []byte
	GitSha            *string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
	RunKey            string
	PredictionModelID pgtype.UUID
}

type DerivedOptimizationRun struct {
	RunID                   string
	CalcuttaID              pgtype.UUID
	Strategy                string
	NSims                   int32
	Seed                    int32
	BudgetPoints            int32
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	DeletedAt               pgtype.Timestamptz
	StrategyGenerationRunID pgtype.UUID
}

type DerivedOptimizedEntry struct {
	ID                    string
	RunKey                *string
	Name                  *string
	CalcuttaID            string
	SimulatedTournamentID pgtype.UUID
	GameOutcomeRunID      pgtype.UUID
	MarketShareRunID      pgtype.UUID
	OptimizerKind         string
	OptimizerParamsJson   []byte
	BidsJson              []byte
	Purpose               *string
	ExcludedEntryName     *string
	StartingStateKey      *string
	ReturnsModelKey       *string
	InvestmentModelKey    *string
	GitSha                *string
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	DeletedAt             pgtype.Timestamptz
}

type DerivedPredictedGameOutcome struct {
	ID           string
	TournamentID string
	GameID       string
	Round        int32
	Team1ID      string
	Team2ID      string
	PTeam1Wins   float64
	PMatchup     float64
	ModelVersion *string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	RunID        pgtype.UUID
}

type DerivedPredictedMarketShare struct {
	ID              string
	CalcuttaID      pgtype.UUID
	TeamID          string
	PredictedShare  float64
	PredictedPoints float64
	CreatedAt       pgtype.Timestamptz
	TournamentID    pgtype.UUID
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
	RunID           pgtype.UUID
}

type DerivedPredictionModel struct {
	ID          string
	Kind        string
	Name        string
	ParamsJson  []byte
	Description *string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type DerivedRunArtifact struct {
	ID                         string
	RunKind                    string
	RunID                      string
	RunKey                     pgtype.UUID
	ArtifactKind               string
	SchemaVersion              string
	StorageUri                 *string
	SummaryJson                []byte
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
	DeletedAt                  pgtype.Timestamptz
	InputMarketShareArtifactID pgtype.UUID
	InputAdvancementArtifactID pgtype.UUID
}

type DerivedRunJob struct {
	ID                string
	RunKind           string
	RunID             string
	RunKey            string
	Status            string
	Attempt           int32
	ParamsJson        []byte
	ProgressJson      []byte
	ProgressUpdatedAt pgtype.Timestamptz
	ClaimedAt         pgtype.Timestamptz
	ClaimedBy         *string
	StartedAt         pgtype.Timestamptz
	FinishedAt        pgtype.Timestamptz
	ErrorMessage      *string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type DerivedRunProgressEvent struct {
	ID          string
	RunKind     string
	RunID       string
	RunKey      pgtype.UUID
	EventKind   string
	Status      *string
	Percent     *float64
	Phase       *string
	Message     *string
	Source      string
	PayloadJson []byte
	CreatedAt   pgtype.Timestamptz
}

type DerivedSimulatedCalcutta struct {
	ID                          string
	Name                        string
	Description                 *string
	TournamentID                string
	BaseCalcuttaID              pgtype.UUID
	StartingStateKey            string
	ExcludedEntryName           *string
	MetadataJson                []byte
	CreatedAt                   pgtype.Timestamptz
	UpdatedAt                   pgtype.Timestamptz
	DeletedAt                   pgtype.Timestamptz
	HighlightedSimulatedEntryID pgtype.UUID
}

type DerivedSimulatedCalcuttaPayout struct {
	ID                  string
	SimulatedCalcuttaID string
	Position            int32
	AmountCents         int32
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	DeletedAt           pgtype.Timestamptz
}

type DerivedSimulatedCalcuttaScoringRule struct {
	ID                  string
	SimulatedCalcuttaID string
	WinIndex            int32
	PointsAwarded       int32
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	DeletedAt           pgtype.Timestamptz
}

type DerivedSimulatedEntry struct {
	ID                  string
	SimulatedCalcuttaID string
	DisplayName         string
	SourceKind          string
	SourceEntryID       pgtype.UUID
	SourceCandidateID   pgtype.UUID
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	DeletedAt           pgtype.Timestamptz
}

type DerivedSimulatedEntryTeam struct {
	ID               string
	SimulatedEntryID string
	TeamID           string
	BidPoints        int32
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}

type DerivedSimulatedTeam struct {
	ID                    string
	TournamentID          string
	SimID                 int32
	TeamID                string
	Wins                  int32
	Byes                  int32
	Eliminated            bool
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	DeletedAt             pgtype.Timestamptz
	SimulatedTournamentID pgtype.UUID
}

type DerivedSimulatedTournament struct {
	ID                   string
	TournamentID         string
	SimulationStateID    string
	NSims                int32
	Seed                 int32
	ProbabilitySourceKey string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	DeletedAt            pgtype.Timestamptz
}

type DerivedSimulationCohort struct {
	ID                      string
	Name                    string
	Description             *string
	GameOutcomesAlgorithmID string
	MarketShareAlgorithmID  string
	OptimizerKey            string
	NSims                   int32
	Seed                    int32
	StartingStateKey        string
	ExcludedEntryName       *string
	ParamsJson              []byte
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	DeletedAt               pgtype.Timestamptz
}

type DerivedSimulationRun struct {
	ID                        string
	RunKey                    string
	SimulationRunBatchID      pgtype.UUID
	CohortID                  string
	CalcuttaID                pgtype.UUID
	GameOutcomeRunID          pgtype.UUID
	MarketShareRunID          pgtype.UUID
	StrategyGenerationRunID   pgtype.UUID
	CalcuttaEvaluationRunID   pgtype.UUID
	StartingStateKey          string
	ExcludedEntryName         *string
	OptimizerKey              *string
	NSims                     *int32
	Seed                      *int32
	OurRank                   *int32
	OurMeanNormalizedPayout   *float64
	OurMedianNormalizedPayout *float64
	OurPTop1                  *float64
	OurPInMoney               *float64
	TotalSimulations          *int32
	RealizedFinishPosition    *int32
	RealizedIsTied            *bool
	RealizedInTheMoney        *bool
	RealizedPayoutCents       *int32
	RealizedTotalPoints       *float64
	Status                    string
	ClaimedAt                 pgtype.Timestamptz
	ClaimedBy                 *string
	ErrorMessage              *string
	CreatedAt                 pgtype.Timestamptz
	UpdatedAt                 pgtype.Timestamptz
	DeletedAt                 pgtype.Timestamptz
	FocusSnapshotEntryID      pgtype.UUID
	SimulatedCalcuttaID       pgtype.UUID
	GameOutcomeSpecJson       []byte
}

type DerivedSimulationRunBatch struct {
	ID                string
	CohortID          string
	Name              *string
	OptimizerKey      *string
	NSims             *int32
	Seed              *int32
	StartingStateKey  string
	ExcludedEntryName *string
	Status            string
	ErrorMessage      *string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
}

type DerivedSimulationState struct {
	ID           string
	TournamentID string
	Source       string
	Description  *string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type DerivedSimulationStateTeam struct {
	ID                string
	SimulationStateID string
	TeamID            string
	Wins              int32
	Byes              int32
	Eliminated        bool
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
}

type DerivedTeam struct {
	ID               string
	CoreTeamID       string
	TournamentID     string
	CoreTournamentID string
	SchoolName       *string
	Seed             int32
	Region           string
	KenpomNet        *float64
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}

type DerivedTournament struct {
	ID                   string
	CoreTournamentID     string
	Season               *int32
	Name                 string
	ImportKey            string
	Rounds               int32
	StartingAt           pgtype.Timestamptz
	FinalFourTopLeft     *string
	FinalFourBottomLeft  *string
	FinalFourTopRight    *string
	FinalFourBottomRight *string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	DeletedAt            pgtype.Timestamptz
}

type DerivedVAlgorithm struct {
	ID          string
	Kind        string
	Name        string
	Description *string
	ParamsJson  []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type DerivedVStrategyGenerationRunBid struct {
	StrategyGenerationRunID string
	RunID                   *string
	TeamID                  string
	BidPoints               int32
	ExpectedRoi             interface{}
	CreatedAt               pgtype.Timestamptz
	DeletedAt               pgtype.Timestamptz
}

type LabEntry struct {
	ID                    string
	InvestmentModelID     string
	CalcuttaID            string
	GameOutcomeKind       string
	GameOutcomeParamsJson []byte
	OptimizerKind         string
	OptimizerParamsJson   []byte
	StartingStateKey      string
	// Optimized bids: [{team_id, bid_points, expected_roi}]. Our optimal allocation given predictions.
	BidsJson  []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	// Market predictions: [{team_id, predicted_market_share, expected_points}]. What model predicts others will bid.
	PredictionsJson []byte
	State           string
}

type LabEntryEvaluation struct {
	EntryID                string
	ModelName              string
	ModelKind              string
	CalcuttaName           string
	StartingStateKey       string
	GameOutcomeKind        string
	OptimizerKind          string
	NSims                  *int32
	Seed                   *int32
	MeanNormalizedPayout   *float64
	MedianNormalizedPayout *float64
	PTop1                  *float64
	PInMoney               *float64
	OurRank                *int32
	EvalCreatedAt          pgtype.Timestamptz
}

type LabEvaluation struct {
	ID                     string
	EntryID                string
	NSims                  int32
	Seed                   int32
	MeanNormalizedPayout   *float64
	MedianNormalizedPayout *float64
	PTop1                  *float64
	PInMoney               *float64
	OurRank                *int32
	SimulatedCalcuttaID    pgtype.UUID
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	DeletedAt              pgtype.Timestamptz
}

type LabEvaluationEntryResult struct {
	ID                   string
	EvaluationID         string
	EntryName            string
	MeanNormalizedPayout *float64
	PTop1                *float64
	PInMoney             *float64
	Rank                 *int32
	CreatedAt            pgtype.Timestamptz
}

type LabInvestmentModel struct {
	ID         string
	Name       string
	Kind       string
	ParamsJson []byte
	Notes      *string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
	// True for oracle/baseline models that should be excluded from training data
	IsBenchmark bool
}

type LabModelLeaderboard struct {
	InvestmentModelID         string
	ModelName                 string
	ModelKind                 string
	NEntries                  int64
	NEntriesWithPredictions   int64
	NEvaluations              int64
	NCalcuttasWithEntries     int64
	NCalcuttasWithEvaluations int64
	AvgMeanPayout             float64
	AvgMedianPayout           float64
	AvgPTop1                  float64
	AvgPInMoney               float64
	FirstEvalAt               interface{}
	LastEvalAt                interface{}
}

type LabPipelineCalcuttaRun struct {
	ID                string
	PipelineRunID     string
	CalcuttaID        string
	EntryID           pgtype.UUID
	Stage             string
	Status            string
	Progress          float64
	ProgressMessage   *string
	PredictionsJobID  pgtype.UUID
	OptimizationJobID pgtype.UUID
	EvaluationJobID   pgtype.UUID
	EvaluationID      pgtype.UUID
	ErrorMessage      *string
	StartedAt         pgtype.Timestamptz
	FinishedAt        pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type LabPipelineRun struct {
	ID                string
	InvestmentModelID string
	TargetCalcuttaIds []string
	BudgetPoints      int32
	OptimizerKind     string
	NSims             int32
	Seed              int32
	ExcludedEntryName *string
	Status            string
	StartedAt         pgtype.Timestamptz
	FinishedAt        pgtype.Timestamptz
	ErrorMessage      *string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}
