// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ownership_details.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listOwnershipDetailsByPortfolioID = `-- name: ListOwnershipDetailsByPortfolioID :many
SELECT
    od.id::text AS id,
    od.portfolio_id,
    od.team_id,
    od.ownership_percentage::float8 AS ownership_percentage,
    od.actual_returns::float8 AS actual_returns,
    od.expected_returns::float8 AS expected_returns,
    od.created_at::timestamptz AS created_at,
    od.updated_at::timestamptz AS updated_at,
    od.deleted_at::timestamptz AS deleted_at,
    tt.id AS tournament_team_id,
    tt.school_id,
    tt.tournament_id,
    tt.seed,
    tt.region,
    tt.byes,
    tt.wins,
    tt.is_eliminated,
    tt.created_at AS team_created_at,
    tt.updated_at AS team_updated_at,
    s.name AS school_name
FROM derived.ownership_details od
JOIN core.teams tt ON od.team_id = tt.id
LEFT JOIN core.schools s ON tt.school_id = s.id
WHERE od.portfolio_id = $1 AND od.deleted_at IS NULL
`

type ListOwnershipDetailsByPortfolioIDRow struct {
	ID                  string
	PortfolioID         string
	TeamID              string
	OwnershipPercentage float64
	ActualReturns       float64
	ExpectedReturns     float64
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	DeletedAt           pgtype.Timestamptz
	TournamentTeamID    string
	SchoolID            string
	TournamentID        string
	Seed                int32
	Region              string
	Byes                int32
	Wins                int32
	IsEliminated        bool
	TeamCreatedAt       pgtype.Timestamptz
	TeamUpdatedAt       pgtype.Timestamptz
	SchoolName          *string
}

func (q *Queries) ListOwnershipDetailsByPortfolioID(ctx context.Context, portfolioID string) ([]ListOwnershipDetailsByPortfolioIDRow, error) {
	rows, err := q.db.Query(ctx, listOwnershipDetailsByPortfolioID, portfolioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOwnershipDetailsByPortfolioIDRow
	for rows.Next() {
		var i ListOwnershipDetailsByPortfolioIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PortfolioID,
			&i.TeamID,
			&i.OwnershipPercentage,
			&i.ActualReturns,
			&i.ExpectedReturns,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TournamentTeamID,
			&i.SchoolID,
			&i.TournamentID,
			&i.Seed,
			&i.Region,
			&i.Byes,
			&i.Wins,
			&i.IsEliminated,
			&i.TeamCreatedAt,
			&i.TeamUpdatedAt,
			&i.SchoolName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnershipDetailsByPortfolioIDs = `-- name: ListOwnershipDetailsByPortfolioIDs :many
SELECT
    od.id::text AS id,
    od.portfolio_id,
    od.team_id,
    od.ownership_percentage::float8 AS ownership_percentage,
    od.actual_returns::float8 AS actual_returns,
    od.expected_returns::float8 AS expected_returns,
    od.created_at::timestamptz AS created_at,
    od.updated_at::timestamptz AS updated_at,
    od.deleted_at::timestamptz AS deleted_at,
    tt.id AS tournament_team_id,
    tt.school_id,
    tt.tournament_id,
    tt.seed,
    tt.region,
    tt.byes,
    tt.wins,
    tt.is_eliminated,
    tt.created_at AS team_created_at,
    tt.updated_at AS team_updated_at,
    s.name AS school_name
FROM derived.ownership_details od
JOIN core.teams tt ON od.team_id = tt.id
LEFT JOIN core.schools s ON tt.school_id = s.id
WHERE od.portfolio_id = ANY($1::uuid[]) AND od.deleted_at IS NULL
`

type ListOwnershipDetailsByPortfolioIDsRow struct {
	ID                  string
	PortfolioID         string
	TeamID              string
	OwnershipPercentage float64
	ActualReturns       float64
	ExpectedReturns     float64
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	DeletedAt           pgtype.Timestamptz
	TournamentTeamID    string
	SchoolID            string
	TournamentID        string
	Seed                int32
	Region              string
	Byes                int32
	Wins                int32
	IsEliminated        bool
	TeamCreatedAt       pgtype.Timestamptz
	TeamUpdatedAt       pgtype.Timestamptz
	SchoolName          *string
}

func (q *Queries) ListOwnershipDetailsByPortfolioIDs(ctx context.Context, portfolioIds []string) ([]ListOwnershipDetailsByPortfolioIDsRow, error) {
	rows, err := q.db.Query(ctx, listOwnershipDetailsByPortfolioIDs, portfolioIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOwnershipDetailsByPortfolioIDsRow
	for rows.Next() {
		var i ListOwnershipDetailsByPortfolioIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.PortfolioID,
			&i.TeamID,
			&i.OwnershipPercentage,
			&i.ActualReturns,
			&i.ExpectedReturns,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TournamentTeamID,
			&i.SchoolID,
			&i.TournamentID,
			&i.Seed,
			&i.Region,
			&i.Byes,
			&i.Wins,
			&i.IsEliminated,
			&i.TeamCreatedAt,
			&i.TeamUpdatedAt,
			&i.SchoolName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
