// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ownership_summaries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOwnershipSummaryByID = `-- name: GetOwnershipSummaryByID :one
SELECT
    id,
    portfolio_id,
    maximum_returns::float8 AS maximum_returns,
    created_at::timestamptz AS created_at,
    updated_at::timestamptz AS updated_at,
    deleted_at::timestamptz AS deleted_at
FROM derived.ownership_summaries
WHERE id = $1 AND deleted_at IS NULL
`

type GetOwnershipSummaryByIDRow struct {
	ID             string
	PortfolioID    string
	MaximumReturns float64
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

func (q *Queries) GetOwnershipSummaryByID(ctx context.Context, id string) (GetOwnershipSummaryByIDRow, error) {
	row := q.db.QueryRow(ctx, getOwnershipSummaryByID, id)
	var i GetOwnershipSummaryByIDRow
	err := row.Scan(
		&i.ID,
		&i.PortfolioID,
		&i.MaximumReturns,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listOwnershipSummariesByPortfolioID = `-- name: ListOwnershipSummariesByPortfolioID :many
SELECT
    id,
    portfolio_id,
    created_at::timestamptz AS created_at,
    updated_at::timestamptz AS updated_at,
    deleted_at::timestamptz AS deleted_at
FROM derived.ownership_summaries
WHERE portfolio_id = $1 AND deleted_at IS NULL
`

type ListOwnershipSummariesByPortfolioIDRow struct {
	ID          string
	PortfolioID string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

func (q *Queries) ListOwnershipSummariesByPortfolioID(ctx context.Context, portfolioID string) ([]ListOwnershipSummariesByPortfolioIDRow, error) {
	rows, err := q.db.Query(ctx, listOwnershipSummariesByPortfolioID, portfolioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOwnershipSummariesByPortfolioIDRow
	for rows.Next() {
		var i ListOwnershipSummariesByPortfolioIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PortfolioID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnershipSummariesByPortfolioIDs = `-- name: ListOwnershipSummariesByPortfolioIDs :many
SELECT
    id,
    portfolio_id,
    created_at::timestamptz AS created_at,
    updated_at::timestamptz AS updated_at,
    deleted_at::timestamptz AS deleted_at
FROM derived.ownership_summaries
WHERE portfolio_id = ANY($1::uuid[]) AND deleted_at IS NULL
`

type ListOwnershipSummariesByPortfolioIDsRow struct {
	ID          string
	PortfolioID string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

func (q *Queries) ListOwnershipSummariesByPortfolioIDs(ctx context.Context, portfolioIds []string) ([]ListOwnershipSummariesByPortfolioIDsRow, error) {
	rows, err := q.db.Query(ctx, listOwnershipSummariesByPortfolioIDs, portfolioIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOwnershipSummariesByPortfolioIDsRow
	for rows.Next() {
		var i ListOwnershipSummariesByPortfolioIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.PortfolioID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
