// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: pool_payouts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayout = `-- name: CreatePayout :exec
INSERT INTO core.payouts (id, pool_id, position, amount_cents, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreatePayoutParams struct {
	ID          string
	PoolID      string
	Position    int32
	AmountCents int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) CreatePayout(ctx context.Context, arg CreatePayoutParams) error {
	_, err := q.db.Exec(ctx, createPayout,
		arg.ID,
		arg.PoolID,
		arg.Position,
		arg.AmountCents,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listPoolPayouts = `-- name: ListPoolPayouts :many
SELECT id, pool_id, position, amount_cents, created_at, updated_at
FROM core.payouts
WHERE pool_id = $1 AND deleted_at IS NULL
ORDER BY position ASC
`

type ListPoolPayoutsRow struct {
	ID          string
	PoolID      string
	Position    int32
	AmountCents int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) ListPoolPayouts(ctx context.Context, poolID string) ([]ListPoolPayoutsRow, error) {
	rows, err := q.db.Query(ctx, listPoolPayouts, poolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPoolPayoutsRow
	for rows.Next() {
		var i ListPoolPayoutsRow
		if err := rows.Scan(
			&i.ID,
			&i.PoolID,
			&i.Position,
			&i.AmountCents,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePayoutsByPoolID = `-- name: SoftDeletePayoutsByPoolID :execrows
UPDATE core.payouts
SET deleted_at = $1, updated_at = $2
WHERE pool_id = $3 AND deleted_at IS NULL
`

type SoftDeletePayoutsByPoolIDParams struct {
	DeletedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	PoolID    string
}

func (q *Queries) SoftDeletePayoutsByPoolID(ctx context.Context, arg SoftDeletePayoutsByPoolIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeletePayoutsByPoolID, arg.DeletedAt, arg.UpdatedAt, arg.PoolID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
