// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: pools.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPool = `-- name: CreatePool :exec
INSERT INTO core.pools (id, tournament_id, owner_id, created_by, name, min_teams, max_teams, max_investment_credits, budget_credits, visibility, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type CreatePoolParams struct {
	ID                   string
	TournamentID         string
	OwnerID              string
	CreatedBy            string
	Name                 string
	MinTeams             int32
	MaxTeams             int32
	MaxInvestmentCredits int32
	BudgetCredits        int32
	Visibility           string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) CreatePool(ctx context.Context, arg CreatePoolParams) error {
	_, err := q.db.Exec(ctx, createPool,
		arg.ID,
		arg.TournamentID,
		arg.OwnerID,
		arg.CreatedBy,
		arg.Name,
		arg.MinTeams,
		arg.MaxTeams,
		arg.MaxInvestmentCredits,
		arg.BudgetCredits,
		arg.Visibility,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getPoolByID = `-- name: GetPoolByID :one
SELECT id, tournament_id, owner_id, created_by, name, min_teams, max_teams, max_investment_credits, budget_credits, visibility, created_at, updated_at
FROM core.pools
WHERE id = $1 AND deleted_at IS NULL
`

type GetPoolByIDRow struct {
	ID                   string
	TournamentID         string
	OwnerID              string
	CreatedBy            string
	Name                 string
	MinTeams             int32
	MaxTeams             int32
	MaxInvestmentCredits int32
	BudgetCredits        int32
	Visibility           string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) GetPoolByID(ctx context.Context, id string) (GetPoolByIDRow, error) {
	row := q.db.QueryRow(ctx, getPoolByID, id)
	var i GetPoolByIDRow
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.OwnerID,
		&i.CreatedBy,
		&i.Name,
		&i.MinTeams,
		&i.MaxTeams,
		&i.MaxInvestmentCredits,
		&i.BudgetCredits,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPoolsByTournament = `-- name: GetPoolsByTournament :many
SELECT id, tournament_id, owner_id, created_by, name, min_teams, max_teams, max_investment_credits, budget_credits, visibility, created_at, updated_at, deleted_at
FROM core.pools
WHERE tournament_id = $1 AND deleted_at IS NULL
`

type GetPoolsByTournamentRow struct {
	ID                   string
	TournamentID         string
	OwnerID              string
	CreatedBy            string
	Name                 string
	MinTeams             int32
	MaxTeams             int32
	MaxInvestmentCredits int32
	BudgetCredits        int32
	Visibility           string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	DeletedAt            pgtype.Timestamptz
}

func (q *Queries) GetPoolsByTournament(ctx context.Context, tournamentID string) ([]GetPoolsByTournamentRow, error) {
	rows, err := q.db.Query(ctx, getPoolsByTournament, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPoolsByTournamentRow
	for rows.Next() {
		var i GetPoolsByTournamentRow
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.OwnerID,
			&i.CreatedBy,
			&i.Name,
			&i.MinTeams,
			&i.MaxTeams,
			&i.MaxInvestmentCredits,
			&i.BudgetCredits,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPools = `-- name: ListPools :many
SELECT id, tournament_id, owner_id, created_by, name, min_teams, max_teams, max_investment_credits, budget_credits, visibility, created_at, updated_at
FROM core.pools
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

type ListPoolsRow struct {
	ID                   string
	TournamentID         string
	OwnerID              string
	CreatedBy            string
	Name                 string
	MinTeams             int32
	MaxTeams             int32
	MaxInvestmentCredits int32
	BudgetCredits        int32
	Visibility           string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) ListPools(ctx context.Context) ([]ListPoolsRow, error) {
	rows, err := q.db.Query(ctx, listPools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPoolsRow
	for rows.Next() {
		var i ListPoolsRow
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.OwnerID,
			&i.CreatedBy,
			&i.Name,
			&i.MinTeams,
			&i.MaxTeams,
			&i.MaxInvestmentCredits,
			&i.BudgetCredits,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPoolsByUserID = `-- name: ListPoolsByUserID :many
SELECT DISTINCT c.id, c.tournament_id, c.owner_id, c.created_by, c.name, c.min_teams, c.max_teams, c.max_investment_credits, c.budget_credits, c.visibility, c.created_at, c.updated_at
FROM core.pools c
WHERE c.deleted_at IS NULL
  AND (c.owner_id = $1
       OR EXISTS (SELECT 1 FROM core.portfolios e
                  WHERE e.pool_id = c.id AND e.user_id = $1 AND e.deleted_at IS NULL)
       OR EXISTS (SELECT 1 FROM core.pool_invitations ci
                  WHERE ci.pool_id = c.id AND ci.user_id = $1 AND ci.status = 'pending' AND ci.deleted_at IS NULL))
ORDER BY c.created_at DESC
`

type ListPoolsByUserIDRow struct {
	ID                   string
	TournamentID         string
	OwnerID              string
	CreatedBy            string
	Name                 string
	MinTeams             int32
	MaxTeams             int32
	MaxInvestmentCredits int32
	BudgetCredits        int32
	Visibility           string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) ListPoolsByUserID(ctx context.Context, ownerID string) ([]ListPoolsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listPoolsByUserID, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPoolsByUserIDRow
	for rows.Next() {
		var i ListPoolsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.OwnerID,
			&i.CreatedBy,
			&i.Name,
			&i.MinTeams,
			&i.MaxTeams,
			&i.MaxInvestmentCredits,
			&i.BudgetCredits,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePool = `-- name: UpdatePool :execrows
UPDATE core.pools
SET tournament_id = $1,
    owner_id = $2,
    name = $3,
    min_teams = $4,
    max_teams = $5,
    max_investment_credits = $6,
    budget_credits = $7,
    visibility = $8,
    updated_at = $9
WHERE id = $10 AND deleted_at IS NULL
`

type UpdatePoolParams struct {
	TournamentID         string
	OwnerID              string
	Name                 string
	MinTeams             int32
	MaxTeams             int32
	MaxInvestmentCredits int32
	BudgetCredits        int32
	Visibility           string
	UpdatedAt            pgtype.Timestamptz
	ID                   string
}

func (q *Queries) UpdatePool(ctx context.Context, arg UpdatePoolParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePool,
		arg.TournamentID,
		arg.OwnerID,
		arg.Name,
		arg.MinTeams,
		arg.MaxTeams,
		arg.MaxInvestmentCredits,
		arg.BudgetCredits,
		arg.Visibility,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
