// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: pool_scoring_rules.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createScoringRule = `-- name: CreateScoringRule :exec
INSERT INTO core.pool_scoring_rules (id, pool_id, win_index, points_awarded, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateScoringRuleParams struct {
	ID            string
	PoolID        string
	WinIndex      int32
	PointsAwarded int32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) CreateScoringRule(ctx context.Context, arg CreateScoringRuleParams) error {
	_, err := q.db.Exec(ctx, createScoringRule,
		arg.ID,
		arg.PoolID,
		arg.WinIndex,
		arg.PointsAwarded,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listScoringRules = `-- name: ListScoringRules :many
SELECT
    id,
    pool_id,
    win_index AS round,
    points_awarded AS points,
    created_at,
    updated_at
FROM core.pool_scoring_rules
WHERE pool_id = $1 AND deleted_at IS NULL
ORDER BY win_index ASC
`

type ListScoringRulesRow struct {
	ID        string
	PoolID    string
	Round     int32
	Points    int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListScoringRules(ctx context.Context, poolID string) ([]ListScoringRulesRow, error) {
	rows, err := q.db.Query(ctx, listScoringRules, poolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScoringRulesRow
	for rows.Next() {
		var i ListScoringRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.PoolID,
			&i.Round,
			&i.Points,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
