// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: pool_invitations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptPoolInvitation = `-- name: AcceptPoolInvitation :execrows
UPDATE core.pool_invitations
SET status = 'accepted',
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) AcceptPoolInvitation(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, acceptPoolInvitation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createPoolInvitation = `-- name: CreatePoolInvitation :exec
INSERT INTO core.pool_invitations (id, pool_id, user_id, invited_by, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
`

type CreatePoolInvitationParams struct {
	ID        string
	PoolID    string
	UserID    string
	InvitedBy string
	Status    string
}

func (q *Queries) CreatePoolInvitation(ctx context.Context, arg CreatePoolInvitationParams) error {
	_, err := q.db.Exec(ctx, createPoolInvitation,
		arg.ID,
		arg.PoolID,
		arg.UserID,
		arg.InvitedBy,
		arg.Status,
	)
	return err
}

const getPendingPoolInvitationByPoolAndUser = `-- name: GetPendingPoolInvitationByPoolAndUser :one
SELECT id, pool_id, user_id, invited_by, status, revoked_at, created_at, updated_at
FROM core.pool_invitations
WHERE pool_id = $1 AND user_id = $2 AND status = 'pending' AND deleted_at IS NULL
`

type GetPendingPoolInvitationByPoolAndUserParams struct {
	PoolID string
	UserID string
}

type GetPendingPoolInvitationByPoolAndUserRow struct {
	ID        string
	PoolID    string
	UserID    string
	InvitedBy string
	Status    string
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetPendingPoolInvitationByPoolAndUser(ctx context.Context, arg GetPendingPoolInvitationByPoolAndUserParams) (GetPendingPoolInvitationByPoolAndUserRow, error) {
	row := q.db.QueryRow(ctx, getPendingPoolInvitationByPoolAndUser, arg.PoolID, arg.UserID)
	var i GetPendingPoolInvitationByPoolAndUserRow
	err := row.Scan(
		&i.ID,
		&i.PoolID,
		&i.UserID,
		&i.InvitedBy,
		&i.Status,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPoolInvitationByPoolAndUser = `-- name: GetPoolInvitationByPoolAndUser :one
SELECT id, pool_id, user_id, invited_by, status, revoked_at, created_at, updated_at
FROM core.pool_invitations
WHERE pool_id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetPoolInvitationByPoolAndUserParams struct {
	PoolID string
	UserID string
}

type GetPoolInvitationByPoolAndUserRow struct {
	ID        string
	PoolID    string
	UserID    string
	InvitedBy string
	Status    string
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetPoolInvitationByPoolAndUser(ctx context.Context, arg GetPoolInvitationByPoolAndUserParams) (GetPoolInvitationByPoolAndUserRow, error) {
	row := q.db.QueryRow(ctx, getPoolInvitationByPoolAndUser, arg.PoolID, arg.UserID)
	var i GetPoolInvitationByPoolAndUserRow
	err := row.Scan(
		&i.ID,
		&i.PoolID,
		&i.UserID,
		&i.InvitedBy,
		&i.Status,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingInvitationsByUserID = `-- name: ListPendingInvitationsByUserID :many
SELECT id, pool_id, user_id, invited_by, status, revoked_at, created_at, updated_at
FROM core.pool_invitations
WHERE user_id = $1 AND status = 'pending' AND deleted_at IS NULL
ORDER BY created_at DESC
`

type ListPendingInvitationsByUserIDRow struct {
	ID        string
	PoolID    string
	UserID    string
	InvitedBy string
	Status    string
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListPendingInvitationsByUserID(ctx context.Context, userID string) ([]ListPendingInvitationsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listPendingInvitationsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingInvitationsByUserIDRow
	for rows.Next() {
		var i ListPendingInvitationsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PoolID,
			&i.UserID,
			&i.InvitedBy,
			&i.Status,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPoolInvitationsByPoolID = `-- name: ListPoolInvitationsByPoolID :many
SELECT id, pool_id, user_id, invited_by, status, revoked_at, created_at, updated_at
FROM core.pool_invitations
WHERE pool_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

type ListPoolInvitationsByPoolIDRow struct {
	ID        string
	PoolID    string
	UserID    string
	InvitedBy string
	Status    string
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListPoolInvitationsByPoolID(ctx context.Context, poolID string) ([]ListPoolInvitationsByPoolIDRow, error) {
	rows, err := q.db.Query(ctx, listPoolInvitationsByPoolID, poolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPoolInvitationsByPoolIDRow
	for rows.Next() {
		var i ListPoolInvitationsByPoolIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PoolID,
			&i.UserID,
			&i.InvitedBy,
			&i.Status,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokePoolInvitation = `-- name: RevokePoolInvitation :execrows
UPDATE core.pool_invitations
SET status = 'revoked',
    revoked_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL AND status = 'pending'
`

func (q *Queries) RevokePoolInvitation(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, revokePoolInvitation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
