// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: schools.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSchool = `-- name: CreateSchool :exec
INSERT INTO core.schools (id, name, slug, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateSchoolParams struct {
	ID        string
	Name      string
	Slug      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateSchool(ctx context.Context, arg CreateSchoolParams) error {
	_, err := q.db.Exec(ctx, createSchool,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getSchoolByID = `-- name: GetSchoolByID :one
SELECT id, name, created_at, updated_at
FROM core.schools
WHERE id = $1 AND deleted_at IS NULL
`

type GetSchoolByIDRow struct {
	ID        string
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetSchoolByID(ctx context.Context, id string) (GetSchoolByIDRow, error) {
	row := q.db.QueryRow(ctx, getSchoolByID, id)
	var i GetSchoolByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSchools = `-- name: ListSchools :many
SELECT id, name, created_at, updated_at
FROM core.schools
WHERE deleted_at IS NULL
ORDER BY name ASC
`

type ListSchoolsRow struct {
	ID        string
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListSchools(ctx context.Context) ([]ListSchoolsRow, error) {
	rows, err := q.db.Query(ctx, listSchools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSchoolsRow
	for rows.Next() {
		var i ListSchoolsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
