// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: team_kenpom_stats.sql

package sqlc

import (
	"context"
)

const upsertTeamKenPomStats = `-- name: UpsertTeamKenPomStats :exec
INSERT INTO core.team_kenpom_stats (team_id, net_rtg, o_rtg, d_rtg, adj_t)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (team_id)
DO UPDATE SET
    net_rtg = EXCLUDED.net_rtg,
    o_rtg = EXCLUDED.o_rtg,
    d_rtg = EXCLUDED.d_rtg,
    adj_t = EXCLUDED.adj_t,
    updated_at = NOW(),
    deleted_at = NULL
`

type UpsertTeamKenPomStatsParams struct {
	TeamID string
	NetRtg *float64
	ORtg   *float64
	DRtg   *float64
	AdjT   *float64
}

func (q *Queries) UpsertTeamKenPomStats(ctx context.Context, arg UpsertTeamKenPomStatsParams) error {
	_, err := q.db.Exec(ctx, upsertTeamKenPomStats,
		arg.TeamID,
		arg.NetRtg,
		arg.ORtg,
		arg.DRtg,
		arg.AdjT,
	)
	return err
}
