// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tournament_imports.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimNextTournamentImport = `-- name: ClaimNextTournamentImport :one
WITH candidate AS (
	SELECT id
	FROM core.tournament_imports
	WHERE deleted_at IS NULL
	  AND core.tournament_imports.finished_at IS NULL
	  AND (
		core.tournament_imports.status = 'pending'
		OR (core.tournament_imports.status = 'running' AND core.tournament_imports.started_at IS NOT NULL AND core.tournament_imports.started_at < $2)
	  )
	ORDER BY created_at ASC
	LIMIT 1
	FOR UPDATE SKIP LOCKED
)
UPDATE core.tournament_imports ti
SET status = 'running',
	started_at = $1,
	finished_at = NULL,
	error_message = NULL,
	import_report = NULL,
	verify_report = NULL,
	updated_at = NOW()
FROM candidate c
WHERE ti.id = c.id
RETURNING ti.id
`

type ClaimNextTournamentImportParams struct {
	Now         pgtype.Timestamptz
	StaleBefore pgtype.Timestamptz
}

func (q *Queries) ClaimNextTournamentImport(ctx context.Context, arg ClaimNextTournamentImportParams) (string, error) {
	row := q.db.QueryRow(ctx, claimNextTournamentImport, arg.Now, arg.StaleBefore)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getTournamentImportArchive = `-- name: GetTournamentImportArchive :one
SELECT archive
FROM core.tournament_imports
WHERE id = $1::uuid AND deleted_at IS NULL
`

func (q *Queries) GetTournamentImportArchive(ctx context.Context, uploadID string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getTournamentImportArchive, uploadID)
	var archive []byte
	err := row.Scan(&archive)
	return archive, err
}

const getTournamentImportStatus = `-- name: GetTournamentImportStatus :one
SELECT
	filename,
	sha256,
	size_bytes,
	status,
	started_at,
	finished_at,
	error_message,
	COALESCE(import_report, '{}'::jsonb)::jsonb AS import_report,
	COALESCE(verify_report, '{}'::jsonb)::jsonb AS verify_report
FROM core.tournament_imports
WHERE id = $1::uuid AND deleted_at IS NULL
`

type GetTournamentImportStatusRow struct {
	Filename     string
	Sha256       string
	SizeBytes    int64
	Status       string
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
	ErrorMessage *string
	ImportReport []byte
	VerifyReport []byte
}

func (q *Queries) GetTournamentImportStatus(ctx context.Context, uploadID string) (GetTournamentImportStatusRow, error) {
	row := q.db.QueryRow(ctx, getTournamentImportStatus, uploadID)
	var i GetTournamentImportStatusRow
	err := row.Scan(
		&i.Filename,
		&i.Sha256,
		&i.SizeBytes,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorMessage,
		&i.ImportReport,
		&i.VerifyReport,
	)
	return i, err
}

const markTournamentImportFailed = `-- name: MarkTournamentImportFailed :exec
UPDATE core.tournament_imports
SET status = 'failed',
	finished_at = NOW(),
	error_message = $1,
	updated_at = NOW()
WHERE id = $2::uuid AND deleted_at IS NULL
`

type MarkTournamentImportFailedParams struct {
	ErrorMessage *string
	UploadID     string
}

func (q *Queries) MarkTournamentImportFailed(ctx context.Context, arg MarkTournamentImportFailedParams) error {
	_, err := q.db.Exec(ctx, markTournamentImportFailed, arg.ErrorMessage, arg.UploadID)
	return err
}

const markTournamentImportSucceeded = `-- name: MarkTournamentImportSucceeded :exec
UPDATE core.tournament_imports
SET status = 'succeeded',
	finished_at = NOW(),
	import_report = $1,
	verify_report = $2,
	updated_at = NOW()
WHERE id = $3::uuid AND deleted_at IS NULL
`

type MarkTournamentImportSucceededParams struct {
	ImportReport []byte
	VerifyReport []byte
	UploadID     string
}

func (q *Queries) MarkTournamentImportSucceeded(ctx context.Context, arg MarkTournamentImportSucceededParams) error {
	_, err := q.db.Exec(ctx, markTournamentImportSucceeded, arg.ImportReport, arg.VerifyReport, arg.UploadID)
	return err
}

const upsertTournamentImport = `-- name: UpsertTournamentImport :one

INSERT INTO core.tournament_imports (filename, sha256, size_bytes, archive, status)
VALUES ($1, $2, $3, $4, 'pending')
ON CONFLICT (sha256) WHERE deleted_at IS NULL
DO UPDATE SET
	filename = EXCLUDED.filename,
	size_bytes = EXCLUDED.size_bytes,
	archive = EXCLUDED.archive,
	status = 'pending',
	started_at = NULL,
	finished_at = NULL,
	error_message = NULL,
	import_report = NULL,
	verify_report = NULL,
	updated_at = NOW()
RETURNING id
`

type UpsertTournamentImportParams struct {
	Filename  string
	Sha256    string
	SizeBytes int64
	Archive   []byte
}

// Tournament imports (formerly bundle_uploads)
func (q *Queries) UpsertTournamentImport(ctx context.Context, arg UpsertTournamentImportParams) (string, error) {
	row := q.db.QueryRow(ctx, upsertTournamentImport,
		arg.Filename,
		arg.Sha256,
		arg.SizeBytes,
		arg.Archive,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
