// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tournaments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTournament = `-- name: CreateTournament :exec
INSERT INTO tournaments (
  id,
  name,
  rounds,
  final_four_top_left,
  final_four_bottom_left,
  final_four_top_right,
  final_four_bottom_right,
  starting_at,
  created_at,
  updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateTournamentParams struct {
	ID                   string
	Name                 string
	Rounds               int32
	FinalFourTopLeft     *string
	FinalFourBottomLeft  *string
	FinalFourTopRight    *string
	FinalFourBottomRight *string
	StartingAt           pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) CreateTournament(ctx context.Context, arg CreateTournamentParams) error {
	_, err := q.db.Exec(ctx, createTournament,
		arg.ID,
		arg.Name,
		arg.Rounds,
		arg.FinalFourTopLeft,
		arg.FinalFourBottomLeft,
		arg.FinalFourTopRight,
		arg.FinalFourBottomRight,
		arg.StartingAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getTournamentByID = `-- name: GetTournamentByID :one
SELECT id, name, rounds,
       final_four_top_left, final_four_bottom_left, final_four_top_right, final_four_bottom_right,
       starting_at,
       created_at, updated_at
FROM tournaments
WHERE id = $1 AND deleted_at IS NULL
`

type GetTournamentByIDRow struct {
	ID                   string
	Name                 string
	Rounds               int32
	FinalFourTopLeft     *string
	FinalFourBottomLeft  *string
	FinalFourTopRight    *string
	FinalFourBottomRight *string
	StartingAt           pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) GetTournamentByID(ctx context.Context, id string) (GetTournamentByIDRow, error) {
	row := q.db.QueryRow(ctx, getTournamentByID, id)
	var i GetTournamentByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Rounds,
		&i.FinalFourTopLeft,
		&i.FinalFourBottomLeft,
		&i.FinalFourTopRight,
		&i.FinalFourBottomRight,
		&i.StartingAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTournaments = `-- name: ListTournaments :many
SELECT id, name, rounds,
       final_four_top_left, final_four_bottom_left, final_four_top_right, final_four_bottom_right,
       starting_at,
       created_at, updated_at
FROM tournaments
WHERE deleted_at IS NULL
ORDER BY name DESC
`

type ListTournamentsRow struct {
	ID                   string
	Name                 string
	Rounds               int32
	FinalFourTopLeft     *string
	FinalFourBottomLeft  *string
	FinalFourTopRight    *string
	FinalFourBottomRight *string
	StartingAt           pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) ListTournaments(ctx context.Context) ([]ListTournamentsRow, error) {
	rows, err := q.db.Query(ctx, listTournaments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTournamentsRow
	for rows.Next() {
		var i ListTournamentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Rounds,
			&i.FinalFourTopLeft,
			&i.FinalFourBottomLeft,
			&i.FinalFourTopRight,
			&i.FinalFourBottomRight,
			&i.StartingAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTournamentStartingAt = `-- name: UpdateTournamentStartingAt :execrows
UPDATE tournaments
SET starting_at = $1,
    updated_at = $2
WHERE id = $3 AND deleted_at IS NULL
`

type UpdateTournamentStartingAtParams struct {
	StartingAt pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	ID         string
}

func (q *Queries) UpdateTournamentStartingAt(ctx context.Context, arg UpdateTournamentStartingAtParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTournamentStartingAt, arg.StartingAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
