// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tournaments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCoreTournament = `-- name: CreateCoreTournament :exec
WITH season_year AS (
  SELECT COALESCE(
    substring($2 from '([0-9]{4})')::int,
    EXTRACT(YEAR FROM NOW())::int
  ) AS year
),
season AS (
  INSERT INTO core.seasons (year)
  SELECT year FROM season_year
  ON CONFLICT (year) DO UPDATE SET year = EXCLUDED.year
  RETURNING id
),
competition AS (
  INSERT INTO core.competitions (name)
  VALUES ('NCAA Men''s')
  ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
  RETURNING id
)
INSERT INTO core.tournaments (
  id,
  competition_id,
  season_id,
  name,
  import_key,
  rounds,
  final_four_top_left,
  final_four_bottom_left,
  final_four_top_right,
  final_four_bottom_right,
  starting_at,
  created_at,
  updated_at
)
SELECT
  $1,
  competition.id,
  season.id,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11
FROM competition
CROSS JOIN season
`

type CreateCoreTournamentParams struct {
	ID                   string
	Name                 string
	ImportKey            string
	Rounds               int32
	FinalFourTopLeft     *string
	FinalFourBottomLeft  *string
	FinalFourTopRight    *string
	FinalFourBottomRight *string
	StartingAt           pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) CreateCoreTournament(ctx context.Context, arg CreateCoreTournamentParams) error {
	_, err := q.db.Exec(ctx, createCoreTournament,
		arg.ID,
		arg.Name,
		arg.ImportKey,
		arg.Rounds,
		arg.FinalFourTopLeft,
		arg.FinalFourBottomLeft,
		arg.FinalFourTopRight,
		arg.FinalFourBottomRight,
		arg.StartingAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getTournamentByID = `-- name: GetTournamentByID :one
SELECT id, name, rounds,
       final_four_top_left, final_four_bottom_left, final_four_top_right, final_four_bottom_right,
       starting_at,
       created_at, updated_at
FROM core.tournaments
WHERE id = $1 AND deleted_at IS NULL
`

type GetTournamentByIDRow struct {
	ID                   string
	Name                 string
	Rounds               int32
	FinalFourTopLeft     *string
	FinalFourBottomLeft  *string
	FinalFourTopRight    *string
	FinalFourBottomRight *string
	StartingAt           pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) GetTournamentByID(ctx context.Context, id string) (GetTournamentByIDRow, error) {
	row := q.db.QueryRow(ctx, getTournamentByID, id)
	var i GetTournamentByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Rounds,
		&i.FinalFourTopLeft,
		&i.FinalFourBottomLeft,
		&i.FinalFourTopRight,
		&i.FinalFourBottomRight,
		&i.StartingAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCompetitions = `-- name: ListCompetitions :many
SELECT id, name
FROM core.competitions
WHERE deleted_at IS NULL
ORDER BY name
`

type ListCompetitionsRow struct {
	ID   string
	Name string
}

func (q *Queries) ListCompetitions(ctx context.Context) ([]ListCompetitionsRow, error) {
	rows, err := q.db.Query(ctx, listCompetitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompetitionsRow
	for rows.Next() {
		var i ListCompetitionsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeasons = `-- name: ListSeasons :many
SELECT id, year
FROM core.seasons
WHERE deleted_at IS NULL
ORDER BY year DESC
`

type ListSeasonsRow struct {
	ID   string
	Year int32
}

func (q *Queries) ListSeasons(ctx context.Context) ([]ListSeasonsRow, error) {
	rows, err := q.db.Query(ctx, listSeasons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSeasonsRow
	for rows.Next() {
		var i ListSeasonsRow
		if err := rows.Scan(&i.ID, &i.Year); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTournaments = `-- name: ListTournaments :many
SELECT id, name, rounds,
       final_four_top_left, final_four_bottom_left, final_four_top_right, final_four_bottom_right,
       starting_at,
       created_at, updated_at
FROM core.tournaments
WHERE deleted_at IS NULL
ORDER BY name DESC
`

type ListTournamentsRow struct {
	ID                   string
	Name                 string
	Rounds               int32
	FinalFourTopLeft     *string
	FinalFourBottomLeft  *string
	FinalFourTopRight    *string
	FinalFourBottomRight *string
	StartingAt           pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) ListTournaments(ctx context.Context) ([]ListTournamentsRow, error) {
	rows, err := q.db.Query(ctx, listTournaments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTournamentsRow
	for rows.Next() {
		var i ListTournamentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Rounds,
			&i.FinalFourTopLeft,
			&i.FinalFourBottomLeft,
			&i.FinalFourTopRight,
			&i.FinalFourBottomRight,
			&i.StartingAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCoreTournamentStartingAt = `-- name: UpdateCoreTournamentStartingAt :execrows
UPDATE core.tournaments
SET starting_at = $1,
    updated_at = $2
WHERE id = $3 AND deleted_at IS NULL
`

type UpdateCoreTournamentStartingAtParams struct {
	StartingAt pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	ID         string
}

func (q *Queries) UpdateCoreTournamentStartingAt(ctx context.Context, arg UpdateCoreTournamentStartingAtParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCoreTournamentStartingAt, arg.StartingAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
