// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO core.users (id, email, first_name, last_name, status, password_hash, external_provider, external_provider_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateUserParams struct {
	ID                 string
	Email              *string
	FirstName          string
	LastName           string
	Status             string
	PasswordHash       *string
	ExternalProvider   *string
	ExternalProviderID *string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.Status,
		arg.PasswordHash,
		arg.ExternalProvider,
		arg.ExternalProviderID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, first_name, last_name, status, password_hash, external_provider, external_provider_id, created_at, updated_at, deleted_at
FROM core.users
WHERE email = $1 AND deleted_at IS NULL
`

type GetUserByEmailRow struct {
	ID                 string
	Email              *string
	FirstName          string
	LastName           string
	Status             string
	PasswordHash       *string
	ExternalProvider   *string
	ExternalProviderID *string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
}

func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Status,
		&i.PasswordHash,
		&i.ExternalProvider,
		&i.ExternalProviderID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByExternalProvider = `-- name: GetUserByExternalProvider :one
SELECT id, email, first_name, last_name, status, password_hash, external_provider, external_provider_id, created_at, updated_at, deleted_at
FROM core.users
WHERE external_provider = $1 AND external_provider_id = $2 AND deleted_at IS NULL
`

type GetUserByExternalProviderParams struct {
	ExternalProvider   *string
	ExternalProviderID *string
}

type GetUserByExternalProviderRow struct {
	ID                 string
	Email              *string
	FirstName          string
	LastName           string
	Status             string
	PasswordHash       *string
	ExternalProvider   *string
	ExternalProviderID *string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
}

func (q *Queries) GetUserByExternalProvider(ctx context.Context, arg GetUserByExternalProviderParams) (GetUserByExternalProviderRow, error) {
	row := q.db.QueryRow(ctx, getUserByExternalProvider, arg.ExternalProvider, arg.ExternalProviderID)
	var i GetUserByExternalProviderRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Status,
		&i.PasswordHash,
		&i.ExternalProvider,
		&i.ExternalProviderID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, first_name, last_name, status, password_hash, external_provider, external_provider_id, created_at, updated_at, deleted_at
FROM core.users
WHERE id = $1 AND deleted_at IS NULL
`

type GetUserByIDRow struct {
	ID                 string
	Email              *string
	FirstName          string
	LastName           string
	Status             string
	PasswordHash       *string
	ExternalProvider   *string
	ExternalProviderID *string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Status,
		&i.PasswordHash,
		&i.ExternalProvider,
		&i.ExternalProviderID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUsersByIDs = `-- name: GetUsersByIDs :many
SELECT id, email, first_name, last_name, status, password_hash, external_provider, external_provider_id, created_at, updated_at, deleted_at
FROM core.users
WHERE id = ANY($1::text[]) AND deleted_at IS NULL
`

type GetUsersByIDsRow struct {
	ID                 string
	Email              *string
	FirstName          string
	LastName           string
	Status             string
	PasswordHash       *string
	ExternalProvider   *string
	ExternalProviderID *string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
}

func (q *Queries) GetUsersByIDs(ctx context.Context, ids []string) ([]GetUsersByIDsRow, error) {
	rows, err := q.db.Query(ctx, getUsersByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersByIDsRow
	for rows.Next() {
		var i GetUsersByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Status,
			&i.PasswordHash,
			&i.ExternalProvider,
			&i.ExternalProviderID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE core.users
SET
  email = $2,
  first_name = $3,
  last_name = $4,
  status = $5,
  password_hash = $6,
  external_provider = $7,
  external_provider_id = $8,
  updated_at = $9,
  deleted_at = $10
WHERE id = $1
`

type UpdateUserParams struct {
	ID                 string
	Email              *string
	FirstName          string
	LastName           string
	Status             string
	PasswordHash       *string
	ExternalProvider   *string
	ExternalProviderID *string
	UpdatedAt          pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.Status,
		arg.PasswordHash,
		arg.ExternalProvider,
		arg.ExternalProviderID,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}
